#!/bin/bash
# ============================================================
# ability-gen.sh — Ability (AB/AE) 代码生成工具
#
# 基于 AbilityEditor.cs 模板精确转译
# 生成 6 类文件 + 修改 5-6 类注册文件
#
# 用法:
#   ability-gen.sh --name <Name> --type <AB|AE> \
#     --fields "M_Field1:type1,M_Field2:type2" \
#     --csv-fields "M_Field1,M_Field2" \
#     [--primary-keys "M_Sign"] \
#     --sync-client <true|false> \
#     [--in-fields "In_StartPoint:Vector3"] \
#     [--project-root <path>]
#
# 示例:
#   ability-gen.sh --name Fireball --type AB \
#     --fields "M_Power:int,M_LifeTime:float,M_EffectName:string" \
#     --csv-fields "M_Power,M_LifeTime,M_EffectName" \
#     --primary-keys "M_Sign" \
#     --sync-client true \
#     --in-fields "In_StartPoint:Vector3"
#
# OUTPUT FILES (供 Phase 4 技术文档 S-05 引用):
#   CREATE: Assets/Scripts/Data/Configs/Ability/{AB|AE}/TemplateM/AbilityM_{Name}.cs
#           — M-data 数据类 (字段定义 + CSV 读取)
#   CREATE: Assets/Scripts/Data/Configs/Ability/{AB|AE}/TemplateM/Select/AbilityM_{Name}_Select.cs
#           — Select 缓存类 (主键查询)
#   CREATE: Assets/Scripts/GamePlay/Server/Ability/System/S{AB|AE}/S{AB|AE}_{Name}System.cs
#           — 服务端 Ability System (S_Ability_Base)
#   CREATE: Assets/Scripts/GamePlay/Client/Ability/System/C{AB|AE}/C{AB|AE}_{Name}System.cs
#           — 客户端 Ability System (条件: --sync-client true)
#   CREATE: Assets/Scripts/Message/Network/Ability/{AB|AE}/Rpc_{Name}.cs
#           — RPC 消息定义
#   CREATE: Assets/Bundle/Configs/Ability/{AB|AE}/AbilityM_{Name}.csv
#           — CSV 数据模板 (空行，需手动填数据)
#   MODIFY: Assets/Scripts/Data/Configs/Ability/{AbilityConfig|AbilityEffectConfig}_AutoGenerated.cs
#           — ConfigId 常量 + Init() 注册 (×2 插入点)
#   MODIFY: Assets/Scripts/Message/Network/{14|15}_Proto_Ability{AB|AE}_Auto.cs
#           — RPC 枚举 + Handler case + Register 注册 (×3 插入点)
#   MODIFY: Assets/Scripts/GamePlay/Server/Ability/ServerAbilityManager_Switch{AB|AE}.cs
#           — switch case 分支
#   MODIFY: Assets/Scripts/GamePlay/Client/Ability/ClientAbilityManager_Switch{AB|AE}.cs
#           — switch case 分支 (条件: --sync-client true)
# ============================================================
set -euo pipefail

# ============================================================
# 参数默认值
# ============================================================
NAME=""
TYPE=""
FIELDS=""
CSV_FIELDS=""
PRIMARY_KEYS=""
SYNC_CLIENT="true"
IN_FIELDS=""
PROJECT_ROOT="."
SHAPE=""               # capsule|sphere|cube (灰盒模式，可选)
SIZE=""                # shape-specific size (auto-default per shape)
COLOR="green"          # named color or r,g,b
MODEL=""               # Asset path → opt-out graybox, use CreateEntity
MODE="create"          # create | update-constants

# ============================================================
# 参数解析
# ============================================================
while [[ $# -gt 0 ]]; do
    case "$1" in
        --name)         NAME="$2";         shift 2 ;;
        --type)         TYPE="$2";         shift 2 ;;
        --fields)       FIELDS="$2";       shift 2 ;;
        --csv-fields)   CSV_FIELDS="$2";   shift 2 ;;
        --primary-keys) PRIMARY_KEYS="$2"; shift 2 ;;
        --sync-client)  SYNC_CLIENT="$2";  shift 2 ;;
        --in-fields)    IN_FIELDS="$2";    shift 2 ;;
        --project-root) PROJECT_ROOT="$2"; shift 2 ;;
        --shape)        SHAPE="$2";        shift 2 ;;
        --size)         SIZE="$2";         shift 2 ;;
        --color)        COLOR="$2";        shift 2 ;;
        --model)        MODEL="$2";        shift 2 ;;
        --mode)         MODE="$2";         shift 2 ;;
        --ugc)          UGC_MODE="true";   shift   ;;
        *) echo "❌ 未知参数: $1"; exit 1 ;;
    esac
done

# ============================================================
# 参数验证
# ============================================================
[[ -z "$NAME" ]]      && echo "❌ --name 必填" && exit 1
[[ -z "$TYPE" ]]      && echo "❌ --type 必填 (AB|AE)" && exit 1

if [[ "$MODE" != "create" && "$MODE" != "update-constants" && "$MODE" != "regen-select" ]]; then
    echo "❌ --mode 必须是 create、update-constants 或 regen-select，当前: $MODE"
    exit 1
fi

if [[ "$MODE" == "create" ]]; then
    [[ -z "$FIELDS" ]]     && echo "❌ --fields 必填" && exit 1
    [[ -z "$CSV_FIELDS" ]] && echo "❌ --csv-fields 必填" && exit 1
fi

if [[ "$TYPE" != "AB" && "$TYPE" != "AE" ]]; then
    echo "❌ --type 必须是 AB 或 AE，当前: $TYPE"
    exit 1
fi

if [[ "$SYNC_CLIENT" != "true" && "$SYNC_CLIENT" != "false" ]]; then
    echo "❌ --sync-client 必须是 true 或 false"
    exit 1
fi

# ============================================================
# 灰盒参数验证 & 默认值
# ============================================================
HAS_GRAYBOX=false
if [[ -n "$SHAPE" ]]; then
    HAS_GRAYBOX=true
    case "$SHAPE" in
        capsule|sphere|cube) ;;
        *) echo "❌ --shape 必须是 capsule|sphere|cube，当前: $SHAPE"; exit 1 ;;
    esac
    # SIZE 默认值
    if [[ -z "$SIZE" ]]; then
        case "$SHAPE" in
            capsule) SIZE="0.4,1.5" ;;
            sphere)  SIZE="0.5" ;;
            cube)    SIZE="1,1,1" ;;
        esac
    fi
    # COLOR 解析
    case "$COLOR" in
        green)  COLOR_CODE="Color.green" ;;
        red)    COLOR_CODE="Color.red" ;;
        blue)   COLOR_CODE="Color.blue" ;;
        yellow) COLOR_CODE="Color.yellow" ;;
        white)  COLOR_CODE="Color.white" ;;
        *)
            IFS=',' read -r _cr _cg _cb <<< "$COLOR"
            COLOR_CODE="new Color(${_cr}f, ${_cg}f, ${_cb}f)"
            ;;
    esac
fi

# ============================================================
# 路径配置（根据 AB/AE 类型）
# ============================================================
# 自动检测项目布局
CODEGEN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_CODEGEN_DIR="$CODEGEN_DIR"
source "$CODEGEN_DIR/path-config.sh"

if [[ "$TYPE" == "AB" ]]; then
    CONFIG_FILE="$PROJECT_ROOT/$SCRIPTS_BASE/Data/Configs/Ability/AbilityConfig_AutoGenerated.cs"
    PROTO_FILE="$PROJECT_ROOT/$SCRIPTS_BASE/Message/Network/14_Proto_AbilityAB_Auto.cs"
    SERVER_SWITCH="$PROJECT_ROOT/$SCRIPTS_BASE/GamePlay/Server/Ability/ServerAbilityManager_SwitchAB.cs"
    CLIENT_SWITCH="$PROJECT_ROOT/$SCRIPTS_BASE/GamePlay/Client/Ability/ClientAbilityManager_SwitchAB.cs"
    MOD_ID=14
    STATE="AB"
    FILE_SIGN="AbilityConfig"
    ABILITY_DATA="IAbilityMData"
    RPC_INTERFACE="IAbilityABCreateRpc"
    CSV_MANAGER_METHOD="GetAbilityABAllCsvRows"
    TEMPLATE_M_DIR="$PROJECT_ROOT/$SCRIPTS_BASE/Data/Configs/Ability/AB/TemplateM"
    SELECT_DIR="$PROJECT_ROOT/$SCRIPTS_BASE/Data/Configs/Ability/AB/TemplateM/Select"
    SERVER_SYSTEM_DIR="$PROJECT_ROOT/$SCRIPTS_BASE/GamePlay/Server/Ability/System/SAB"
    CLIENT_SYSTEM_DIR="$PROJECT_ROOT/$SCRIPTS_BASE/GamePlay/Client/Ability/System/CAB"
    RPC_DIR="$PROJECT_ROOT/$SCRIPTS_BASE/Message/Network/Ability/AB"
else
    CONFIG_FILE="$PROJECT_ROOT/$SCRIPTS_BASE/Data/Configs/Ability/AbilityEffectConfig_AutoGenerated.cs"
    PROTO_FILE="$PROJECT_ROOT/$SCRIPTS_BASE/Message/Network/15_Proto_AbilityAE_Auto.cs"
    SERVER_SWITCH="$PROJECT_ROOT/$SCRIPTS_BASE/GamePlay/Server/Ability/ServerAbilityManager_SwitchAE.cs"
    CLIENT_SWITCH="$PROJECT_ROOT/$SCRIPTS_BASE/GamePlay/Client/Ability/ClientAbilityManager_SwitchAE.cs"
    MOD_ID=15
    STATE="AE"
    FILE_SIGN="AbilityEffectConfig"
    ABILITY_DATA="IAbilityEffectMData"
    RPC_INTERFACE="IAbilityAECreateRpc"
    CSV_MANAGER_METHOD="GetAbilityAEAllCsvRows"
    TEMPLATE_M_DIR="$PROJECT_ROOT/$SCRIPTS_BASE/Data/Configs/Ability/AE/TemplateM"
    SELECT_DIR="$PROJECT_ROOT/$SCRIPTS_BASE/Data/Configs/Ability/AE/TemplateM/Select"
    SERVER_SYSTEM_DIR="$PROJECT_ROOT/$SCRIPTS_BASE/GamePlay/Server/Ability/System/SAE"
    CLIENT_SYSTEM_DIR="$PROJECT_ROOT/$SCRIPTS_BASE/GamePlay/Client/Ability/System/CAE"
    RPC_DIR="$PROJECT_ROOT/$SCRIPTS_BASE/Message/Network/Ability/AE"
fi

CSV_DIR="$PROJECT_ROOT/$BUNDLE_CONFIGS/Ability/${TYPE}"

# 输出文件路径
ABILITY_M_FILE="$TEMPLATE_M_DIR/AbilityM_${NAME}.cs"
SELECT_FILE="$SELECT_DIR/AbilityM_${NAME}_Select.cs"
SERVER_FILE="$SERVER_SYSTEM_DIR/S${TYPE}_${NAME}System.cs"
CLIENT_FILE="$CLIENT_SYSTEM_DIR/C${TYPE}_${NAME}System.cs"
RPC_FILE="$RPC_DIR/Rpc_${NAME}.cs"
CSV_FILE="$CSV_DIR/AbilityM_${NAME}.csv"

# 模板变量（PGC 默认值，UGC 钩子可覆写）
SERVER_AB_NS="Sofunny.BiuBiuBiu2.ServerGamePlay"
CLIENT_AB_NS="Sofunny.BiuBiuBiu2.ClientGamePlay"
NETWORK_NS="Sofunny.BiuBiuBiu2.NetworkMessage"
SERVER_SYSTEM_CLASS="S${TYPE}_${NAME}System"
CLIENT_SYSTEM_CLASS="C${TYPE}_${NAME}System"
RPC_OUTER_CLASS="Proto_Ability${STATE}_Auto"
RPC_ID_PREFIX="Proto_Ability${STATE}_Auto.TargetRpc_${NAME}"
RPC_FUNC_REF=""  # 留空表示使用 PGC 的 Rpc_${NAME}_FuncID 引用
MOD_ID_REF="ModID"
EXTRA_USING=""

# ── UGC 钩子：覆写路径/NS/类名/ID ──
if [[ "${UGC_MODE:-}" == "true" && ! -f "$_CODEGEN_DIR/ugc/ability-gen-ugc.sh" ]]; then
    echo "⚠️ UGC hook 不存在: ugc/ability-gen-ugc.sh，回退 PGC 流程"
    UGC_MODE=false
fi
if [[ "${UGC_MODE:-}" == "true" ]]; then
    source "$_CODEGEN_DIR/ugc/ability-gen-ugc.sh" config
fi

# ============================================================
# update-constants 模式：从 CSV 读取常量，替换 Select 文件占位符
# ============================================================
if [[ "$MODE" == "update-constants" ]]; then
    echo "🔄 update-constants 模式：更新 AbilityM_${NAME}_Select.cs 常量"

    [[ ! -f "$CSV_FILE" ]] && echo "❌ CSV 文件不存在: $CSV_FILE" && exit 1
    [[ ! -f "$SELECT_FILE" ]] && echo "❌ Select 文件不存在: $SELECT_FILE" && exit 1

    # 读取 CSV 头部，确认 ID 和 RowSign 列的索引（剥离 UTF-8 BOM 和 CR）
    csv_header=$(head -1 "$CSV_FILE" | LC_ALL=C sed 's/^\xef\xbb\xbf//' | tr -d '\r')
    IFS=',' read -ra csv_cols <<< "$csv_header"
    id_col=-1
    sign_col=-1
    for ci in "${!csv_cols[@]}"; do
        col="${csv_cols[$ci]}"
        [[ "$col" == "ID" ]] && id_col=$ci
        [[ "$col" == "RowSign" ]] && sign_col=$ci
    done
    if [[ $id_col -lt 0 || $sign_col -lt 0 ]]; then
        echo "❌ CSV 头部未找到 ID 或 RowSign 列（实际: $csv_header）"
        exit 1
    fi

    # 生成 ID 常量块和 Sign 常量块
    id_block=""
    sign_block=""
    while IFS= read -r row || [[ -n "$row" ]]; do
        [[ -z "$row" ]] && continue
        IFS=',' read -ra cells <<< "$row"
        row_id="${cells[$id_col]}"
        row_sign="${cells[$sign_col]}"
        [[ -z "$row_id" || -z "$row_sign" ]] && continue
        id_block="${id_block}        public const byte ID_${row_sign} = ${row_id};"$'\n'
        sign_block="${sign_block}        public const string Sign_${row_sign} = \"${row_sign}\";"$'\n'
    done < <(tail -n +2 "$CSV_FILE")

    if [[ -z "$id_block" && -z "$sign_block" ]]; then
        echo "⚠️  CSV 中没有数据行，常量块为空，跳过更新"
        exit 0
    fi

    # 将占位符替换为常量块（用 awk 逐行处理，避免 sed 多行问题）
    tmp_select="${SELECT_FILE}.tmp.$$"
    awk \
        -v id_blk="$id_block" \
        -v sign_blk="$sign_block" \
        '{
            if ($0 ~ /\/\/ \[ID_CONSTANTS_PLACEHOLDER\]/) {
                # 移除尾随换行，然后输出常量块
                printf "%s", id_blk
                next
            }
            if ($0 ~ /\/\/ \[SIGN_CONSTANTS_PLACEHOLDER\]/) {
                printf "%s", sign_blk
                next
            }
            print
        }' "$SELECT_FILE" > "$tmp_select"
    mv "$tmp_select" "$SELECT_FILE"

    echo "✅ 已更新常量："
    echo "$id_block"
    echo "$sign_block"
    echo "   文件: $SELECT_FILE"
    exit 0
fi



# 在第一个匹配 pattern 的行之前插入多行文本（跨平台）
insert_before() {
    local pattern="$1"
    local text="$2"
    local file="$3"
    local tmp="${file}.tmp.$$"
    local txt_file="${file}.ins.$$"
    printf '%s\n' "$text" > "$txt_file"
    awk -v pat="$pattern" -v tf="$txt_file" '
        !done && $0 ~ pat {
            while ((getline line < tf) > 0) print line
            done = 1
        }
        { print }
    ' "$file" > "$tmp"
    mv "$tmp" "$file"
    rm -f "$txt_file"
}

# 在最后一个匹配 pattern 的行之后插入多行文本
insert_after_last() {
    local pattern="$1"
    local text="$2"
    local file="$3"
    local tmp="${file}.tmp.$$"
    local last_line
    last_line=$(grep -n "$pattern" "$file" | tail -1 | cut -d: -f1)
    if [[ -n "$last_line" ]]; then
        local txt_file="${file}.ins.$$"
        printf '%s\n' "$text" > "$txt_file"
        awk -v ln="$last_line" -v tf="$txt_file" '
            NR==ln { print; while ((getline line < tf) > 0) print line; next }
            { print }
        ' "$file" > "$tmp"
        mv "$tmp" "$file"
        rm -f "$txt_file"
    else
        echo "⚠️  未找到匹配: $pattern in $file"
    fi
}

# 解析字段列表 "M_Power:int,M_LifeTime:float" 为数组
# 结果存入全局 _PARSED_NAMES / _PARSED_TYPES（兼容 bash 3.2，无 local -n）
parse_fields() {
    local input="$1"
    _PARSED_NAMES=()
    _PARSED_TYPES=()
    IFS=',' read -ra pairs <<< "$input"
    for pair in "${pairs[@]}"; do
        IFS=':' read -r fname ftype <<< "$pair"
        _PARSED_NAMES+=("$fname")
        _PARSED_TYPES+=("$ftype")
    done
}

# C# 类型到 AssetCsvManager 解析代码
csv_parse_expr() {
    local fname="$1"
    local ftype="$2"
    if [[ "$ftype" == "string" ]]; then
        echo "AssetCsvManager.GetCsvRowValue(row, \"${fname}\")"
    else
        echo "AssetCsvManager.ParseValue<${ftype}>(AssetCsvManager.GetCsvRowValue(row, \"${fname}\"))"
    fi
}

# C# 类型到 ByteBuffer 读取方法
buffer_read_method() {
    local ftype="$1"
    case "$ftype" in
        int)      echo "ReadInt" ;;
        uint)     echo "ReadUInt" ;;
        short)    echo "ReadShort" ;;
        ushort)   echo "ReadUShort" ;;
        long)     echo "ReadLong" ;;
        ulong)    echo "ReadULong" ;;
        float)    echo "ReadFloat" ;;
        double)   echo "ReadDouble" ;;
        byte)     echo "ReadByte" ;;
        sbyte)    echo "ReadSByte" ;;
        bool)     echo "ReadBool" ;;
        string)   echo "ReadString" ;;
        Vector3)  echo "ReadVector3" ;;
        Vector2)  echo "ReadVector2" ;;
        Quaternion) echo "ReadQuaternion" ;;
        *)        echo "Read /* TODO: unknown type $ftype */" ;;
    esac
}

# ============================================================
# 解析字段
# ============================================================
FIELD_NAMES=()
FIELD_TYPES=()
parse_fields "$FIELDS"
FIELD_NAMES=("${_PARSED_NAMES[@]}")
FIELD_TYPES=("${_PARSED_TYPES[@]}")

CSV_FIELD_LIST=()
IFS=',' read -ra CSV_FIELD_LIST <<< "$CSV_FIELDS"

PK_NAMES=()
if [[ -n "$PRIMARY_KEYS" ]]; then
    IFS=',' read -ra PK_NAMES <<< "$PRIMARY_KEYS"
fi

IN_FIELD_NAMES=()
IN_FIELD_TYPES=()
if [[ -n "$IN_FIELDS" ]]; then
    parse_fields "$IN_FIELDS"
    IN_FIELD_NAMES=("${_PARSED_NAMES[@]}")
    IN_FIELD_TYPES=("${_PARSED_TYPES[@]}")
fi

# ============================================================
# 自动注入 M_Sign（Select 缓存系统必需）
# ============================================================
HAS_M_SIGN=false
for fn in "${FIELD_NAMES[@]}"; do
    [[ "$fn" == "M_Sign" ]] && HAS_M_SIGN=true && break
done
if [[ "$HAS_M_SIGN" == "false" ]]; then
    # M_Sign 只加到字段列表（M_ 文件和 CopyInstanceData 需要）
    # 不加到 CSV_FIELD_LIST（CSV 中是 RowSign，Select 解析用 rowSign 赋值）
    FIELD_NAMES=("M_Sign" "${FIELD_NAMES[@]}")
    FIELD_TYPES=("string" "${FIELD_TYPES[@]}")
fi

# ============================================================
# regen-select 模式：从 CSV + M 模板 .cs 重新构建字段数组
# （create 模式的字段数组已由 --fields 参数构建完毕）
# ============================================================
if [[ "$MODE" == "regen-select" ]]; then
    [[ ! -f "$CSV_FILE" ]]       && echo "❌ CSV 文件不存在: $CSV_FILE"       && exit 1
    [[ ! -f "$ABILITY_M_FILE" ]] && echo "❌ M 模板文件不存在: $ABILITY_M_FILE" && exit 1
    echo "🔄 regen-select：从 CSV + M 模板重建字段数组"
    # 1. 从 CSV 头部重建 CSV_FIELD_LIST（跳过 ID / RowSign）
    CSV_FIELD_LIST=()
    # 剥离 UTF-8 BOM（0xEF 0xBB 0xBF）并去除行末 CR
    csv_header=$(head -1 "$CSV_FILE" | LC_ALL=C sed 's/^\xef\xbb\xbf//' | tr -d '\r')
    IFS=',' read -ra raw_headers <<< "$csv_header"
    for col in "${raw_headers[@]}"; do
        col=$(echo "$col" | tr -d '\r\n ')
        [[ "$col" == "ID" || "$col" == "RowSign" ]] && continue
        CSV_FIELD_LIST+=("$col")
    done
    # 2. 从 M 模板 .cs grep 各字段类型，重建 FIELD_NAMES / FIELD_TYPES
    FIELD_NAMES=()
    FIELD_TYPES=()
    for csv_f in "${CSV_FIELD_LIST[@]}"; do
        # 防御：grep 无匹配返回 1，加 || true 避免 set -e 提前退出
        f_type=$(grep -oE "public [a-zA-Z0-9_]+ ${csv_f};" "$ABILITY_M_FILE" 2>/dev/null \
            | awk '{print $2}' | head -1) || true
        if [[ -z "$f_type" ]]; then
            echo "⚠️  字段 ${csv_f} 未在 M 模板中找到类型，默认 float"
            f_type="float"
        fi
        FIELD_NAMES+=("$csv_f")
        FIELD_TYPES+=("$f_type")
    done
    # 3. 重新注入 M_Sign（CSV 中无此列，但 Select 的 CopyInstanceData 需要）
    HAS_M_SIGN_RS=false
    for fn in "${FIELD_NAMES[@]}"; do
        [[ "$fn" == "M_Sign" ]] && HAS_M_SIGN_RS=true && break
    done
    if [[ "$HAS_M_SIGN_RS" == "false" ]]; then
        FIELD_NAMES=("M_Sign" "${FIELD_NAMES[@]}")
        FIELD_TYPES=("string" "${FIELD_TYPES[@]}")
    fi
    echo "   字段列表: ${FIELD_NAMES[*]}"
    echo "   CSV 字段: ${CSV_FIELD_LIST[*]}"
fi

# ============================================================
# 文件存在性检查（防覆盖）
# ============================================================
CREATED_FILES=()
check_file_not_exists() {
    if [[ -f "$1" ]]; then
        echo "❌ 文件已存在: $1"
        exit 1
    fi
}

if [[ "$MODE" == "create" ]]; then
    check_file_not_exists "$ABILITY_M_FILE"
    check_file_not_exists "$SELECT_FILE"
    check_file_not_exists "$SERVER_FILE"
    check_file_not_exists "$RPC_FILE"
    check_file_not_exists "$CSV_FILE"
    if [[ "$SYNC_CLIENT" == "true" ]]; then
        check_file_not_exists "$CLIENT_FILE"
    fi

    if [[ "${UGC_MODE:-}" == "true" ]]; then
        # UGC 幂等检查：UGC 注册文件中是否已有此 Name
        if grep -q "UGC${NAME}" "$UGC_ABILITY_CONFIG" 2>/dev/null; then
            echo "❌ ${NAME} 已在 AbilityConfig_UGC 中注册"
            exit 1
        fi
        # 确认 UGC 注册目标文件存在
        for f in "$UGC_ABILITY_CONFIG" "$UGC_CORE_WORLD" "$UGC_SERVER_WORLD"; do
            [[ ! -f "$f" ]] && echo "❌ UGC 注册目标文件不存在: $f" && exit 1
        done
        if [[ "$SYNC_CLIENT" == "true" ]]; then
            [[ ! -f "$UGC_CLIENT_WORLD" ]] && echo "❌ UGC 注册目标文件不存在: $UGC_CLIENT_WORLD" && exit 1
        fi
    else
        # PGC 幂等检查：注册文件中是否已有此 Name
        if grep -q "AbilityM_${NAME}" "$CONFIG_FILE" 2>/dev/null; then
            echo "❌ ${NAME} 已在 ${FILE_SIGN} 中注册"
            exit 1
        fi
        # 确认注册目标文件存在
        for f in "$CONFIG_FILE" "$PROTO_FILE" "$SERVER_SWITCH"; do
            [[ ! -f "$f" ]] && echo "❌ 注册目标文件不存在: $f" && exit 1
        done
        if [[ "$SYNC_CLIENT" == "true" ]]; then
            [[ ! -f "$CLIENT_SWITCH" ]] && echo "❌ 注册目标文件不存在: $CLIENT_SWITCH" && exit 1
        fi
    fi
fi

# ============================================================
# ID 分配（仅 create 模式）
# ============================================================
if [[ "$MODE" == "create" ]]; then
  if [[ "${UGC_MODE:-}" != "true" ]]; then
    # PGC ID 分配
    # AB: ID 在 10000-19999; AE: ID >= 20000
    if [[ "$TYPE" == "AB" ]]; then
        MAX_CONFIG_ID=$(grep -oE 'public const ushort [A-Za-z_0-9]+ = [0-9]+' "$CONFIG_FILE" \
            | grep -oE '[0-9]+$' | awk '$1 >= 10000 && $1 < 20000' | sort -n | tail -1 || echo "")
        [[ -z "$MAX_CONFIG_ID" ]] && MAX_CONFIG_ID=10000
    else
        MAX_CONFIG_ID=$(grep -oE 'public const ushort [A-Za-z_0-9]+ = [0-9]+' "$CONFIG_FILE" \
            | grep -oE '[0-9]+$' | awk '$1 >= 20000' | sort -n | tail -1 || echo "")
        [[ -z "$MAX_CONFIG_ID" ]] && MAX_CONFIG_ID=20000
    fi
    NEXT_CONFIG_ID=$((MAX_CONFIG_ID + 1))

    MAX_FUNC_ID=$(grep -oE 'public const byte [A-Za-z_]+_FuncID = [0-9]+' "$PROTO_FILE" \
        | grep -oE '[0-9]+$' | sort -n | tail -1 || echo "")
    [[ -z "$MAX_FUNC_ID" ]] && MAX_FUNC_ID=0
    NEXT_FUNC_ID=$((MAX_FUNC_ID + 1))
  fi
  # UGC 的 NEXT_CONFIG_ID / NEXT_FUNC_ID 已在 config 钩子中设置

    echo "📝 配置信息:"
    echo "   名称: $NAME"
    echo "   类型: $TYPE ($STATE)"
    echo "   ConfigId: $NEXT_CONFIG_ID"
    echo "   FuncId: $NEXT_FUNC_ID"
    echo "   同步客户端: $SYNC_CLIENT"
    echo ""
fi

# ============================================================
# 创建目录
# ============================================================
mkdir -p "$SELECT_DIR"
if [[ "$MODE" == "create" ]]; then
    mkdir -p "$TEMPLATE_M_DIR" "$SERVER_SYSTEM_DIR" "$RPC_DIR" "$CSV_DIR"
    if [[ "$SYNC_CLIENT" == "true" ]]; then
        mkdir -p "$CLIENT_SYSTEM_DIR"
    fi

# ============================================================
# 1. 创建 AbilityM_{Name}.cs
# ============================================================
echo "📄 创建 AbilityM_${NAME}.cs ..."

{
    cat <<'HEADER'
// 该文件由 ability-gen.sh 自动生成，AI 不得删除该注释
using System;
using Sofunny.BiuBiuBiu2.Template;
using UnityEngine;

HEADER
    echo "namespace Sofunny.BiuBiuBiu2.Data {"
    echo "    public partial class AbilityM_${NAME} : AbilityMData {"
    echo '        //M_模板数据 来源 csv'

    # M_ 字段声明
    for i in "${!FIELD_NAMES[@]}"; do
        echo "        public ${FIELD_TYPES[$i]} ${FIELD_NAMES[$i]};"
    done

    echo "    }"

    # AbilityIn — AB 类型
    if [[ "$TYPE" == "AB" ]]; then
        echo ""
        if [[ ${#IN_FIELD_NAMES[@]} -gt 0 ]]; then
            echo "    public class AbilityIn_${NAME} : IAbilityInData {"
            echo "        // In_输入数据"
            for i in "${!IN_FIELD_NAMES[@]}"; do
                echo "        public ${IN_FIELD_TYPES[$i]} ${IN_FIELD_NAMES[$i]};"
            done
            echo "    }"
        else
            echo "    public class AbilityIn_${NAME} : IAbilityInData {"
            echo "        // In_输入数据"
            echo "    }"
        fi
    fi

    # AbilityIn — AE 类型（壳）
    if [[ "$TYPE" == "AE" ]]; then
        echo ""
        echo "    public partial class AbilityIn_${NAME} : IAbilityEffectInData {"
        echo "        // In_输入数据"
        echo "    }"
    fi

    echo "}"
} > "$ABILITY_M_FILE"
CREATED_FILES+=("$ABILITY_M_FILE")
fi  # end create-mode: AbilityM_.cs

# ============================================================
# 2. 创建/重新生成 AbilityM_{Name}_Select.cs
# ============================================================
echo "📄 创建 AbilityM_${NAME}_Select.cs ..."

{
    # --- 头部 ---
    cat <<SELHEAD
// 该文件由 ability-gen.sh 自动生成，AI 不得删除该注释
using System;
using System.Collections.Generic;
using Sofunny.BiuBiuBiu2.Asset;
#if UNITY_EDITOR
using UnityEditor;
#endif
using UnityEngine;

namespace Sofunny.BiuBiuBiu2.Data {
    public partial class AbilityM_${NAME} {
        public const string AbilityTypeID = ${FILE_SIGN}.${STATE}_${NAME};
        public const ushort ConfigId = ${FILE_SIGN}.${NAME};
        private static Dictionary<byte, AbilityM_${NAME}> idCache = new Dictionary<byte, AbilityM_${NAME}>();
        private static Dictionary<string, AbilityM_${NAME}> signCache = new Dictionary<string, AbilityM_${NAME}>();
        private static List<AbilityM_${NAME}> loadingCallbacks = new List<AbilityM_${NAME}>();
        private static bool IsCsvLoaded = false;
        private static bool isLoading = false;
        private Action callBack;
        private bool IsSetCsvData = false;
        public override string GetTypeID() {
            return AbilityTypeID;
        }
        public override ushort GetConfigId() {
            return ConfigId;
        }
        public override byte GetRowID() {
            return K_ID;
        }
        public override string GetRowSign() {
            return K_RowSign;
        }

        /// <summary>
        /// CSV ID常量映射（自动生成，对应CSV的ID列）
        /// 新建时为空，填入CSV数据后由工具重新生成
        /// </summary>
        // [ID_CONSTANTS_PLACEHOLDER]

        /// <summary>
        /// CSV Sign 常量映射（自动生成，对应CSV的RowSign列）
        /// 新建时为空，填入CSV数据后由工具重新生成
        /// </summary>
        // [SIGN_CONSTANTS_PLACEHOLDER]

        /// <summary>
        /// ID查询主键
        /// </summary>
        [NonSerialized]
        public byte K_ID = 0;
        /// <summary>
        /// Sign 查询主键
        /// </summary>
        [NonSerialized]
        public string K_RowSign = "";
SELHEAD

    # K_ 主键字段
    if [[ ${#PK_NAMES[@]} -gt 0 ]]; then
        echo ""
        echo "        /// <summary>"
        echo "        /// 普通主键字段（K_ID=0 K_RowSign=\"\" 时生效）"
        echo "        /// </summary>"
        for pk in "${PK_NAMES[@]}"; do
            # 找到对应的类型
            pk_type="string"
            for i in "${!FIELD_NAMES[@]}"; do
                if [[ "${FIELD_NAMES[$i]}" == "$pk" ]]; then
                    pk_type="${FIELD_TYPES[$i]}"
                    break
                fi
            done
            k_name="${pk/M_/K_}"
            echo "        [NonSerialized]"
            echo "        public ${pk_type} ${k_name};"
        done
    fi

    # --- ClearCache ---
    cat <<SELCLEAR

        public static void ClearCache() {
            idCache.Clear();
            signCache.Clear();
            loadingCallbacks.Clear();
            IsCsvLoaded = false;
            isLoading = false;
            Debug.Log("已清除 AbilityM_${NAME} 实例缓存");
        }

        override public void Select(Action callBack) {
            if (IsSetCsvData) {
                callBack.Invoke();
                return;
            }
            this.callBack = callBack;
            if (IsCsvLoaded) {
                DoSelectFromCache();
                return;
            }
            loadingCallbacks.Add(this);
            if (isLoading) {
                return;
            }
            LoadCsvAndCacheAll(OnLoadComplete);
        }

        private static void OnLoadComplete() {
            foreach (var abilityM in loadingCallbacks) {
                abilityM.DoSelectFromCache();
            }
            loadingCallbacks.Clear();
            isLoading = false;
        }

        private void DoSelectFromCache() {
            AbilityM_${NAME} target = null;
            if (this.K_ID != 0) {
                idCache.TryGetValue(this.K_ID, out target);
            } else if (this.K_RowSign != "") {
                signCache.TryGetValue(this.K_RowSign, out target);
            }
SELCLEAR

    # DoSelectFromCache — 多主键查询
    if [[ ${#PK_NAMES[@]} -gt 0 ]]; then
        # 构建 FindByMultiKeys 调用参数
        find_args=""
        for pk in "${PK_NAMES[@]}"; do
            k_name="${pk/M_/K_}"
            [[ -n "$find_args" ]] && find_args="${find_args}, "
            find_args="${find_args}this.${k_name}"
        done
        echo "            else {"
        echo "                target = FindByMultiKeys(${find_args});"
        echo "            }"
    else
        echo '            else {'
        echo "                Debug.LogError(\$\"[AbilityM_${NAME}] 无普通主键，必须赋值K_ID后调用Select()\");"
        echo '            }'
    fi

    cat <<SELCACHE2
            if (target != null) {
                this.K_ID = target.K_ID;
                this.K_RowSign = target.K_RowSign;
                CopyInstanceData(target);
                this.IsSetCsvData = true;
            } else {
                Debug.LogError(\$"AbilityM_${NAME} 查询未找到：K_ID={this.K_ID} 或 K_RowSign={this.K_RowSign}");
            }
            callBack?.Invoke();
            callBack = null;
        }
SELCACHE2

    # --- FindByMultiKeys ---
    if [[ ${#PK_NAMES[@]} -gt 0 ]]; then
        # 构建参数列表
        params=""
        for pk in "${PK_NAMES[@]}"; do
            pk_type="string"
            for i in "${!FIELD_NAMES[@]}"; do
                if [[ "${FIELD_NAMES[$i]}" == "$pk" ]]; then
                    pk_type="${FIELD_TYPES[$i]}"
                    break
                fi
            done
            k_name="${pk/M_/K_}"
            [[ -n "$params" ]] && params="${params}, "
            params="${params}${pk_type} ${k_name}"
        done

        echo "        private static AbilityM_${NAME} FindByMultiKeys(${params}) {"
        echo "            foreach (var instance in idCache.Values) {"
        echo "                bool isMatch = true;"
        for pk in "${PK_NAMES[@]}"; do
            k_name="${pk/M_/K_}"
            echo "                if (${k_name} != instance.${k_name}) {"
            echo "                    isMatch = false;"
            echo "                }"
        done
        echo "                if (isMatch) {"
        echo "                    return instance;"
        echo "                }"
        echo "            }"
        echo "            return null;"
        echo "        }"
        echo ""
    fi

    # --- LoadCsvAndCacheAll ---
    cat <<SELLOAD
        private static void LoadCsvAndCacheAll(Action onLoadComplete) {
            isLoading = true;
            var time = Time.realtimeSinceStartup;
            AssetCsvManager.${CSV_MANAGER_METHOD}("AbilityM_${NAME}", allRows => {
                if (allRows == null || allRows.Count == 0) {
                    Debug.LogError(\$"全量加载 CSV 失败：AbilityM_${NAME}");
                    onLoadComplete?.Invoke();
                    return;
                }
                idCache.Clear();
                signCache.Clear();
                foreach (var row in allRows) {
                    var idStr = AssetCsvManager.GetCsvRowValue(row, "ID");
                    if (!byte.TryParse(idStr, out byte rowId)) {
                        Debug.LogError(\$"CSV 行 ID 格式错误：AbilityM_${NAME} → {idStr}");
                        continue;
                    }
                    if (idCache.ContainsKey(rowId)) {
                        Debug.LogError(\$"CSV AbilityM_${NAME} 行 ID重复：{rowId}（已跳过）");
                        continue;
                    }
                    var rowSign = AssetCsvManager.GetCsvRowValue(row, "RowSign");
                    var instance = new AbilityM_${NAME}();
                    instance.K_ID = rowId;
                    instance.K_RowSign = rowSign;
SELLOAD

    # 字段解析
    for csv_f in "${CSV_FIELD_LIST[@]}"; do
        # 查找字段类型
        f_type=""
        for i in "${!FIELD_NAMES[@]}"; do
            if [[ "${FIELD_NAMES[$i]}" == "$csv_f" ]]; then
                f_type="${FIELD_TYPES[$i]}"
                break
            fi
        done
        if [[ -z "$f_type" ]]; then
            echo "                    // WARNING: CSV field $csv_f not found in --fields"
            continue
        fi
        parse_code=$(csv_parse_expr "$csv_f" "$f_type")
        echo "                    instance.${csv_f} = ${parse_code};"
    done

    # M_Sign 赋值（值来自 RowSign，不从 CSV 列解析）
    echo "                    instance.M_Sign = rowSign;"

    # 主键赋值
    for pk in "${PK_NAMES[@]}"; do
        k_name="${pk/M_/K_}"
        echo "                    instance.${k_name} = instance.${pk};"
    done

    cat <<SELLOAD2
                    instance.IsSetCsvData = true;
                    idCache[rowId] = instance;
                    signCache[rowSign] = instance;
                }
                IsCsvLoaded = true;
#if UNITY_EDITOR
                Debug.Log(\$"CSV全量加载完成：AbilityM_${NAME} → 缓存 {idCache.Count}个实例 （耗时 {Time.realtimeSinceStartup - time:F2}秒）");
#endif
                onLoadComplete?.Invoke();
            });
        }
SELLOAD2

    # --- CopyInstanceData ---
    echo "        private void CopyInstanceData(AbilityM_${NAME} source) {"
    for pk in "${PK_NAMES[@]}"; do
        k_name="${pk/M_/K_}"
        echo "            this.${k_name} = source.${k_name};"
    done
    for i in "${!FIELD_NAMES[@]}"; do
        echo "            this.${FIELD_NAMES[$i]} = source.${FIELD_NAMES[$i]};"
    done
    echo "        }"
    echo ""

    # --- CreateForKey ---
    if [[ ${#PK_NAMES[@]} -gt 0 ]]; then
        params=""
        find_args=""
        for pk in "${PK_NAMES[@]}"; do
            pk_type="string"
            for i in "${!FIELD_NAMES[@]}"; do
                if [[ "${FIELD_NAMES[$i]}" == "$pk" ]]; then
                    pk_type="${FIELD_TYPES[$i]}"
                    break
                fi
            done
            k_name="${pk/M_/K_}"
            [[ -n "$params" ]] && params="${params}, "
            params="${params}${pk_type} ${k_name}"
            [[ -n "$find_args" ]] && find_args="${find_args}, "
            find_args="${find_args}${k_name}"
        done

        echo "        public static AbilityM_${NAME} CreateForKey(${params}) {"
        echo "            if (IsCsvLoaded) {"
        echo "                var cachedInstance = FindByMultiKeys(${find_args});"
        echo "                if (cachedInstance != null) {"
        echo "                    return cachedInstance;"
        echo "                }"
        echo "            }"
        echo "            var newData = CreateSO();"
        for pk in "${PK_NAMES[@]}"; do
            k_name="${pk/M_/K_}"
            echo "            newData.${k_name} = ${k_name};"
        done
        echo "            return newData;"
        echo "        }"
        echo ""
    fi

    # --- CreateForID / CreateForSign / CreateSO ---
    cat <<SELCREATE
        public static AbilityM_${NAME} CreateForID(byte id) {
            if (IsCsvLoaded && idCache.TryGetValue(id, out var cachedInstance)) {
                return cachedInstance;
            }
            var newData = CreateSO();
            newData.K_ID = id;
            return newData;
        }

        public static AbilityM_${NAME} CreateForSign(string sign) {
            if (IsCsvLoaded && signCache.TryGetValue(sign, out var cachedInstance)) {
                return cachedInstance;
            }
            var newData = CreateSO();
            newData.K_RowSign = sign;
            return newData;
        }

        private static AbilityM_${NAME} CreateSO() {
#if UNITY_EDITOR
           var url = \$"{AssetURL.AbilitySO}SO/${STATE}/AbilityM_${NAME}.asset";
           var so = AssetDatabase.LoadAssetAtPath<AbilityM_${NAME}>(url);
           if (so != null && so.IsEditorUseSO) {
              so.IsSetCsvData = true;
              return so;
           }
#endif
           return new AbilityM_${NAME}();
        }
    }
}
SELCREATE
} > "$SELECT_FILE"
CREATED_FILES+=("$SELECT_FILE")

# regen-select 模式：Select 文件已重新生成，退出
if [[ "$MODE" == "regen-select" ]]; then
    echo "✅ 已重新生成 Select 文件: $SELECT_FILE"
    echo "⚠️  请在 Unity 编辑器中重新聚焦窗口或执行 AssetDatabase.Refresh() 以使更改生效"
    exit 0
fi

# ============================================================
# 3. 创建 S{AB|AE}_{Name}System.cs
# ============================================================
echo "📄 创建 S${TYPE}_${NAME}System.cs ..."

{
    cat <<SVRHEAD
// 该文件由 ability-gen.sh 自动生成，AI 不得删除该注释
$(if $HAS_GRAYBOX; then echo "using Sofunny.BiuBiuBiu2.Component;"; fi)
using Sofunny.BiuBiuBiu2.Data;
using Sofunny.BiuBiuBiu2.Message;
using Sofunny.BiuBiuBiu2.NetworkMessage;
using Sofunny.BiuBiuBiu2.ServerMessage;
$(if [[ -n "$EXTRA_USING" ]]; then echo "$EXTRA_USING"; fi)
using UnityEngine;

namespace ${SERVER_AB_NS} {
    public class ${SERVER_SYSTEM_CLASS} : S_Ability_Base {
        private AbilityM_${NAME} useMData;
SVRHEAD

    # AB 特有: InData
    if [[ "$TYPE" == "AB" ]]; then
        echo "        private AbilityIn_${NAME} useInData;"
    fi

    echo ""
    echo "        protected override void OnAwake() {"
    echo "            base.OnAwake();"
    echo "            useMData = (AbilityM_${NAME})MData;"

    if [[ "$TYPE" == "AB" ]]; then
        echo "            useInData = (AbilityIn_${NAME})InData;"
        echo "            // 设置 AB 初始位置"
        echo "            iEntity.SetPoint(useInData.In_StartPoint);"
    fi

    echo "            AddComponents();"
    echo "        }"
    echo ""
    echo "        protected override void OnClear() {"
    echo "            useMData = null;"
    if [[ "$TYPE" == "AB" ]]; then
        echo "            useInData = null;"
    fi
    echo "        }"
    echo ""

    # OnStart — RPC 同步
    echo "        /// <summary>"
    echo "        ///  服务器实体创建方式有两种："
    echo "        /// </summary>"
    echo "        protected override void OnStart() {"
    if [[ "$SYNC_CLIENT" == "true" ]]; then
        if [[ "$TYPE" == "AB" ]]; then
            echo "             // 短效的同步用这个，长效的请使用 ServerNetworkSync"
            echo "            RPCAbility(new ${RPC_OUTER_CLASS}.Rpc_${NAME}() {"
            echo "                configId = ConfigID,"
            echo "                rowId = RowId,"
            for i in "${!IN_FIELD_NAMES[@]}"; do
                local_name="${IN_FIELD_NAMES[$i]}"
                rpc_name="${local_name/In_/}"
                rpc_name="$(echo "${rpc_name:0:1}" | tr '[:upper:]' '[:lower:]')${rpc_name:1}"
                echo "                ${rpc_name} = useInData.${local_name}, // 不需要进行坐标同步可以删除 (RPC 里面也要删掉)"
            done
            echo "            });"
        else
            echo "            RPCAbility(new ${RPC_OUTER_CLASS}.Rpc_${NAME}() {"            echo "                configId = ConfigID,"
            echo "                rowId = RowId,"
            echo "                gpoId = TargetGPO.GetGpoID(),"
            echo "            });"
        fi
    else
        echo "             // 此技能不同步到客户端 (SyncCreateCAB=false), 如果有播放特效同步到客户端的需求，可以使用 RPCAbility(new Proto_Ability.Rpc_PlayEffect()"
    fi
    echo "            // 如果需要创建实体（正式资源或本地 prefab）："
    if $HAS_GRAYBOX; then
        echo "            // 灰盒 Entity (ability-gen.sh --shape $SHAPE)"
        if [[ -n "$MODEL" ]]; then
            echo "            CreateEntity(AttributeData.Sign + \"Server\");"
        else
            echo "            var root = new GameObject(\"${NAME}_Server\");"
            echo "            root.layer = LayerData.ServerLayer;"
            case "$SHAPE" in
                capsule)
                    IFS=',' read -r _r _h <<< "$SIZE"
                    echo "            var col = root.AddComponent<CapsuleCollider>();"
                    echo "            col.radius = ${_r}f;"
                    echo "            col.height = ${_h}f;"
                    ;;
                sphere)
                    echo "            var col = root.AddComponent<SphereCollider>();"
                    echo "            col.radius = ${SIZE}f;"
                    ;;
                cube)
                    IFS=',' read -r _x _y _z <<< "$SIZE"
                    echo "            var col = root.AddComponent<BoxCollider>();"
                    echo "            col.size = new Vector3(${_x}f, ${_y}f, ${_z}f);"
                    ;;
            esac
            echo "            var rootHit = root.AddComponent<HitType>();"
            echo "            rootHit.Part = GPOData.PartEnum.RootBody;"
            echo "            rootHit.Layer = GPOData.LayerEnum.World;"
            echo "            SetGameObjectEntity(root, StageData.GameWorldLayerType.Ability);"
        fi
    else
        echo "            // CreateEntity(AttributeData.Sign + \"Server\");"
        echo "            // 如果没有本地资源，需要在运行时创建 cube 等简单物体作为实体对象"
        echo "            // SetGameObjectEntity 使用方式参阅 core-rules.md 文档 ## 第四部分：程序化 Entity 构建规范"
        echo "            // ### Rule 15：服务端程序化 Entity 不得保留 Renderer，只需要有 Collider"
        echo "            // 服务端的 Collider 需要设置 gameobject.layer = LayerData.ServerLayer; 以便于服务端的技能系统等模块通过 LayerMask 来过滤检测"
        echo "            // SetGameObjectEntity();"
        echo "            // Entity 设置成功会触发 OnLoadEntityEnd"
    fi
    echo "        }"
    echo ""

    # AddComponents
    echo "        override protected void AddComponents() {"
    echo "            base.AddComponents();"
    echo "             // 示例：生命周期组件中设置时间，时间到后调用技能删除"
    echo "             AddComponent<TimeReduce>(new TimeReduce.InitData {"
    echo "                 LifeTime = useMData.M_LifeTime,"
    echo "                 CallBack = () => {"
    echo "                    // 删除服务端上的技能，在调用该方法后，会同步通知客户端进行删除，请自己调整该事件的调用位置"
    echo "                    MsgRegister.Dispatcher(new SM_Ability.RemoveAbility {"
    echo "                        AbilityId = AbilityId"
    echo "                    });"
    echo "                 }"
    echo "             });"

    if [[ "$SYNC_CLIENT" == "true" ]]; then
        if [[ "$TYPE" == "AB" ]]; then
            echo "             // 长效 AB 调用的方法，会自动进行重连，和位置同步，如果只是播放一下特效不需要考虑重连可以删除下面相关的代码"
            echo "             // 长效 AB 的组件，需要继承 ServerNetworkComponentBase 而不是 ComponentBase"
            echo "             //AddComponent<ServerNetworkSync>(new ServerNetworkSync.InitData {"
            echo "             //   CallBack = OnSyncSpawnProto, // 常驻类型"
            echo "             //   SyncDistance = 300, // 区域剔除的同步距离"
            echo "             //});"
            echo "             //AddComponent<ServerNetworkTransform>();"
        else
            echo "             // 长效 AB 的组件，需要继承 ServerNetworkComponentBase 而不是 ComponentBase"
            echo "             // AE 需要使用这个做同步"
            echo "             AddComponent<ServerNetworkSync>(new ServerNetworkSync.InitData {"
            echo "                CallBack = OnSyncSpawnProto, // 常驻类型"
            echo "                SyncDistance = 300, // 区域剔除的同步距离"
            echo "             });"
            echo "             AddComponent<ServerNetworkTransform>();"
        fi
    fi
    echo "        }"

    # 重连同步函数（仅 sync-client）
    if [[ "$SYNC_CLIENT" == "true" ]]; then
        echo ""
        echo "        // 重连同步的函数，不需要可以删除"
        echo "        void OnSyncSpawnProto(ServerNetworkSync sync) {"
        echo "             var fireGpoId = FireGPO == null ? (ushort)0 : (ushort)FireGPO.GpoID;"
        echo "             sync.SetSpawnRPC(new Proto_Ability.TargetRpc_PlayAbility {"
        echo "                  fireGpoId = fireGpoId,"
        echo "                  abilityId = AbilityId,"
        echo "                  protoDoc = sync.SerializeProto(new ${RPC_OUTER_CLASS}.Rpc_${NAME} {"
        if [[ "$TYPE" == "AB" ]]; then
            echo "                       startPoint = iEntity.GetPoint(), // 不需要同步位置可以删除 (RPC 里面也要删掉)，主要这边要使用 iEntity.GetPoint() 而不是 inData.In_StartPoint"
        else
            echo "                       gpoId = TargetGPO.GetGpoID(),"
        fi
        echo "                       configId = ConfigID,"
        echo "                       rowId = RowId,"
        echo "                  })"
        echo "              });"
        echo "        }"
    fi

    echo "    }"
    echo "}"
} > "$SERVER_FILE"
CREATED_FILES+=("$SERVER_FILE")

# ============================================================
# 4. 创建 C{AB|AE}_{Name}System.cs（仅 sync-client=true）
# ============================================================
if [[ "$SYNC_CLIENT" == "true" ]]; then
    echo "📄 创建 C${TYPE}_${NAME}System.cs ..."

    {
        cat <<CLIHEAD
// 该文件由 ability-gen.sh 自动生成，AI 不得删除该注释
using Sofunny.BiuBiuBiu2.Data;
using Sofunny.BiuBiuBiu2.NetworkMessage;
using Sofunny.BiuBiuBiu2.ClientMessage;
using Sofunny.BiuBiuBiu2.Message;
$(if [[ -n "$EXTRA_USING" ]]; then echo "$EXTRA_USING"; fi)
$(if $HAS_GRAYBOX; then echo "using UnityEngine;"; fi)

namespace ${CLIENT_AB_NS} {
    public class ${CLIENT_SYSTEM_CLASS} : C_Ability_Base {
        private ${RPC_OUTER_CLASS}.Rpc_${NAME} useInData;
CLIHEAD

        if [[ "$TYPE" == "AB" ]]; then
            echo "        private AbilityM_${NAME} useMData;"
        fi

        echo ""
        echo "        protected override void OnAwake() {"
        echo "            base.OnAwake();"
        echo "            useInData = (${RPC_OUTER_CLASS}.Rpc_${NAME})InData;"

        if [[ "$TYPE" == "AB" ]]; then
            echo "            useMData = (AbilityM_${NAME})MData;"
            echo "             // 设置 AB 初始位置，有需要可以打开下面的注释，需要从网络协议上进行下发"
            echo "            iEntity.SetPoint(useInData.startPoint);"
        fi

        echo "            AddComponents();"
        echo "        }"
        echo ""
        echo "        /// <summary>"
        echo "        ///  客户端实体创建方式有两种："
        echo "        /// </summary>"
        echo "        protected override void OnStart() {"
        echo "            base.OnStart();"
        if $HAS_GRAYBOX; then
            if [[ -n "$MODEL" ]]; then
                echo "            CreateEntity(MData.GetEffectSign());"
            else
                local prim_type
                case "$SHAPE" in
                    capsule) prim_type="Capsule" ;;
                    sphere)  prim_type="Sphere" ;;
                    cube)    prim_type="Cube" ;;
                esac
                echo "            // 灰盒 Entity (ability-gen.sh --shape $SHAPE)"
                echo "            var root = GameObject.CreatePrimitive(PrimitiveType.${prim_type});"
                echo "            root.name = \"${NAME}_Client\";"
                echo "            root.layer = LayerData.ClientLayer;"
                case "$SHAPE" in
                    capsule)
                        IFS=',' read -r _r _h <<< "$SIZE"
                        echo "            root.transform.localScale = new Vector3(${_r}f * 2f, ${_h}f / 2f, ${_r}f * 2f);"
                        ;;
                    sphere)
                        echo "            root.transform.localScale = Vector3.one * ${SIZE}f * 2f;"
                        ;;
                    cube)
                        IFS=',' read -r _x _y _z <<< "$SIZE"
                        echo "            root.transform.localScale = new Vector3(${_x}f, ${_y}f, ${_z}f);"
                        ;;
                esac
                echo "            var renderer = root.GetComponent<Renderer>();"
                echo "            if (renderer != null) renderer.material.color = ${COLOR_CODE};"
                echo "            SetGameObjectEntity(root, StageData.GameWorldLayerType.Ability);"
            fi
        else
            echo "            // 如果模板里面有表现要加载，可以打开下面的注释"
            echo "            CreateEntity(MData.GetEffectSign()); // 正式资源或本地 prefab 的加载方式"
            echo "            // 如果没有本地资源，需要在运行时创建 cube 等简单物体作为实体对象"
            echo "            // SetGameObjectEntity 使用方式参阅 core-rules.md 文档 ## 第四部分：程序化 Entity 构建规范"
            echo "            // 客户端的 collider 需要设置 gameobject.layer = LayerData.ClientLayer; 以便于客户端的技能系统等模块通过 LayerMask 来过滤检测"
            echo "            // SetGameObjectEntity();"
            echo "            // Entity 设置成功会触发 OnLoadEntityEnd"
        fi
        echo "        }"
        echo ""
        echo "        protected override void OnClear() {"
        echo "            base.OnClear();"

        if [[ "$TYPE" == "AB" ]]; then
            echo "            useMData = null;"
        fi

        echo "        }"
        echo ""
        echo "        protected override void OnLoadEntityEnd(IEntity iEnter) {"
        echo "            base.OnLoadEntityEnd(iEnter);"
        echo "        }"
        echo ""

        # AddComponents — AB 和 AE 差异化
        echo "        private void AddComponents() {"
        if [[ "$TYPE" == "AB" ]]; then
            echo "             // 长效 AB 调用的方法，会自动进行网络状态，重连相关的逻辑对接"
            echo "            //AddComponent<ClientAbilityNetworkBehaviour>();"
            echo "             // 长效 AB 调用的方法，会自动和服务器进行位置同步"
            echo "            //AddComponent<ClientNetworkTransform>();"
            echo "             // 长效 AB 服务器会帮助管理生命周期，短效需要自己维护 LifeTime, 如果是长效可以删除下面的生命周期"
            echo "            AddComponent<TimeReduce>(new TimeReduce.InitData {"
            echo "                LifeTime = useMData.M_LifeTime,"
            echo "                CallBack = LifeTimeEnd"
            echo "            });"
        else
            echo "            // 长效 AB 调用的方法，会自动进行网络状态，重连相关的逻辑对接"
            echo "            AddComponent<ClientAbilityNetworkBehaviour>();"
            echo "            // 长效 AB 调用的方法，会自动和服务器进行位置同步"
            echo "            AddComponent<ClientNetworkTransform>();"
            echo "            AddComponent<ClientSetPointForTargetGPO>(new ClientSetPointForTargetGPO.InitData {"
            echo "                  TargetGPOId = useInData.gpoId,"
            echo "            });"
        fi
        echo "        }"
        echo ""

        # LifeTimeEnd（仅 AB）
        if [[ "$TYPE" == "AB" ]]; then
            echo "        private void LifeTimeEnd() {"
            echo "            this.Dispatcher(new CE_Ability.RemoveAbility() {"
            echo "                AbilityId = this.AbilityId"
            echo "            });"
            echo "        }"
        fi

        echo "    }"
        echo "}"
    } > "$CLIENT_FILE"
    CREATED_FILES+=("$CLIENT_FILE")
fi

# ============================================================
# 5. 创建 Rpc_{Name}.cs
# ============================================================
echo "📄 创建 Rpc_${NAME}.cs ..."

# RPC FuncID 值：UGC 用字面量数字，PGC 用引用常量名
_FUNC_ID_VALUE="${RPC_FUNC_REF:-Rpc_${NAME}_FuncID}"

{
    cat <<RPCHEAD
// 该文件由 ability-gen.sh 自动生成，AI 不得删除该注释
using Sofunny.BiuBiuBiu2.Data;
using Sofunny.BiuBiuBiu2.Message;
using UnityEngine;

namespace ${NETWORK_NS} {
    public partial class ${RPC_OUTER_CLASS} {
        public struct Rpc_${NAME} : ${RPC_INTERFACE} {
            public const string ID = "${RPC_ID_PREFIX}";
            public int GetChannel() => NetworkData.Channels.Reliable;
            public string GetID() => ID;
            public byte GetRowID() => rowId;
            public ushort GetConfigID() => configId;
            public const byte FuncID = ${_FUNC_ID_VALUE};
            public ushort configId;
            public byte rowId;
RPCHEAD

    # AB 特有字段
    if [[ "$TYPE" == "AB" ]]; then
        for i in "${!IN_FIELD_NAMES[@]}"; do
            local_name="${IN_FIELD_NAMES[$i]}"
            rpc_name="${local_name/In_/}"
            rpc_name="$(echo "${rpc_name:0:1}" | tr '[:upper:]' '[:lower:]')${rpc_name:1}"
            echo "            public ${IN_FIELD_TYPES[$i]} ${rpc_name};"
        done
    fi

    # AE 特有字段
    if [[ "$TYPE" == "AE" ]]; then
        echo "            public int gpoId;"
    fi

    # Serialize
    echo ""
    echo "            public void Serialize(ByteBuffer buffer) {"
    echo "                buffer.Write(${MOD_ID_REF});"
    echo "                buffer.Write(FuncID);"
    echo "                buffer.Write(configId);"
    echo "                buffer.Write(rowId);"

    if [[ "$TYPE" == "AB" ]]; then
        for i in "${!IN_FIELD_NAMES[@]}"; do
            local_name="${IN_FIELD_NAMES[$i]}"
            rpc_name="${local_name/In_/}"
            rpc_name="$(echo "${rpc_name:0:1}" | tr '[:upper:]' '[:lower:]')${rpc_name:1}"
            echo "                buffer.Write(${rpc_name});"
        done
    fi
    if [[ "$TYPE" == "AE" ]]; then
        echo "                buffer.Write(gpoId);"
    fi

    echo "            }"

    # UnSerialize
    echo ""
    echo "            public void UnSerialize(ByteBuffer buffer) {"
    echo "                configId = buffer.ReadUShort();"
    echo "                rowId = buffer.ReadByte();"

    if [[ "$TYPE" == "AB" ]]; then
        for i in "${!IN_FIELD_NAMES[@]}"; do
            local_name="${IN_FIELD_NAMES[$i]}"
            rpc_name="${local_name/In_/}"
            rpc_name="$(echo "${rpc_name:0:1}" | tr '[:upper:]' '[:lower:]')${rpc_name:1}"
            read_method=$(buffer_read_method "${IN_FIELD_TYPES[$i]}")
            echo "                ${rpc_name} = buffer.${read_method}();"
        done
    fi
    if [[ "$TYPE" == "AE" ]]; then
        echo "                gpoId = buffer.ReadInt();"
    fi

    echo "            }"
    echo "        }"
    echo "    }"
    echo "}"
} > "$RPC_FILE"
CREATED_FILES+=("$RPC_FILE")

# ============================================================
# 6. 创建 AbilityM_{Name}.csv
# ============================================================
echo "📄 创建 AbilityM_${NAME}.csv ..."

{
    # 构建 CSV 头部: ID,RowSign,csv_fields...
    header="ID,RowSign"
    for csv_f in "${CSV_FIELD_LIST[@]}"; do
        header="${header},${csv_f}"
    done
    echo "$header"
} > "$CSV_FILE"
CREATED_FILES+=("$CSV_FILE")

# ============================================================
# 注册阶段
# ============================================================
echo ""
echo "🔧 修改注册文件..."
MODIFIED_FILES=()

if [[ "${UGC_MODE:-}" == "true" ]]; then
# ── UGC MODIFY: 注册枢纽插入 ──
source "$_CODEGEN_DIR/ugc/ability-gen-ugc.sh" modify
else

# ============================================================
# 7. 修改 Config 文件（4 处插入）
# ============================================================
echo "   → ${FILE_SIGN}_AutoGenerated.cs ..."

# 7a. 插入 const ushort（在最后一个 const ushort 之后）
insert_after_last "public const ushort" \
    "        public const ushort ${NAME} = ${NEXT_CONFIG_ID};" \
    "$CONFIG_FILE"

# 7b. 插入 const string（在最后一个 public const string 之后）
insert_after_last "public const string ${STATE}_" \
    "        public const string ${STATE}_${NAME} = \"${STATE}_${NAME}\";" \
    "$CONFIG_FILE"

# 7c. 插入 switch case (configSign)（在最后一个 CreateForSign 的 break; 之后）
# Config 文件的 switch 没有 default:，所以在最后一个 case 的 break 后追加
LAST_SIGN_LINE=$(grep -n "CreateForSign" "$CONFIG_FILE" | tail -1 | cut -d: -f1)
if [[ -n "$LAST_SIGN_LINE" ]]; then
    SIGN_BREAK_LINE=$((LAST_SIGN_LINE + 1))
    CONFIG_SIGN_TEXT="                case ${STATE}_${NAME}:
                    mData = AbilityM_${NAME}.CreateForSign(rowSign);
                    break;"
    local_tmp="${CONFIG_FILE}.tmp.$$"
    local_txt="${CONFIG_FILE}.ins.sign.$$"
    printf '%s\n' "$CONFIG_SIGN_TEXT" > "$local_txt"
    awk -v ln="$SIGN_BREAK_LINE" -v tf="$local_txt" '
        NR==ln { print; while ((getline line < tf) > 0) print line; next }
        { print }
    ' "$CONFIG_FILE" > "$local_tmp"
    mv "$local_tmp" "$CONFIG_FILE"
    rm -f "$local_txt"
fi

# 7d. 插入 switch case (configId)（在最后一个 CreateForID 的 break; 之后）
LAST_ID_LINE=$(grep -n "CreateForID" "$CONFIG_FILE" | tail -1 | cut -d: -f1)
if [[ -n "$LAST_ID_LINE" ]]; then
    ID_BREAK_LINE=$((LAST_ID_LINE + 1))
    CONFIG_ID_TEXT="                case ${NAME}:
                    mData = AbilityM_${NAME}.CreateForID(rowId);
                    break;"
    local_tmp="${CONFIG_FILE}.tmp.$$"
    local_txt="${CONFIG_FILE}.ins.id.$$"
    printf '%s\n' "$CONFIG_ID_TEXT" > "$local_txt"
    awk -v ln="$ID_BREAK_LINE" -v tf="$local_txt" '
        NR==ln { print; while ((getline line < tf) > 0) print line; next }
        { print }
    ' "$CONFIG_FILE" > "$local_tmp"
    mv "$local_tmp" "$CONFIG_FILE"
    rm -f "$local_txt"
fi

MODIFIED_FILES+=("$CONFIG_FILE")

# ============================================================
# 8. 修改 ServerAbilityManager Switch
# ============================================================
echo "   → ServerAbilityManager_Switch${TYPE}.cs ..."

if ! grep -q "AbilityM_${NAME}.AbilityTypeID" "$SERVER_SWITCH"; then
    SERVER_CASE_TEXT="                case AbilityM_${NAME}.AbilityTypeID:
                    system = AddSystem<S${TYPE}_${NAME}System>(callBack);
                    break;"
    insert_before "default:" "$SERVER_CASE_TEXT" "$SERVER_SWITCH"
fi
MODIFIED_FILES+=("$SERVER_SWITCH")

# ============================================================
# 9. 修改 ClientAbilityManager Switch（仅 sync-client=true）
# ============================================================
if [[ "$SYNC_CLIENT" == "true" ]]; then
    echo "   → ClientAbilityManager_Switch${TYPE}.cs ..."

    if ! grep -q "Rpc_${NAME}.ID" "$CLIENT_SWITCH"; then
        CLIENT_CASE_TEXT="                case Proto_Ability${STATE}_Auto.Rpc_${NAME}.ID:
                    system = AddSystem<C${TYPE}_${NAME}System>(callBack);
                    break;"
        insert_before "default:" "$CLIENT_CASE_TEXT" "$CLIENT_SWITCH"
    fi
    MODIFIED_FILES+=("$CLIENT_SWITCH")
fi

# ============================================================
# 10. 修改 Proto 文件（FuncID + switch case）
# ============================================================
echo "   → ${MOD_ID}_Proto_Ability${STATE}_Auto.cs ..."

if ! grep -q "Rpc_${NAME}_FuncID" "$PROTO_FILE"; then
    # 10a. 插入 FuncID 常量
    insert_after_last "public const byte.*_FuncID" \
        "        public const byte Rpc_${NAME}_FuncID = ${NEXT_FUNC_ID};" \
        "$PROTO_FILE"

    # 10b. 插入 switch case
    PROTO_CASE_TEXT="                case Rpc_${NAME}_FuncID:
                    doc = new Rpc_${NAME}();
                    break;"
    insert_before "default:" "$PROTO_CASE_TEXT" "$PROTO_FILE"
fi
MODIFIED_FILES+=("$PROTO_FILE")

fi  # end UGC/PGC MODIFY branch

# ============================================================
# 输出摘要
# ============================================================
echo ""
echo "✅ ability-gen.sh 执行完成！"
echo ""
echo "📁 创建的文件:"
for f in "${CREATED_FILES[@]}"; do
    echo "   + $f"
done
echo ""
echo "📝 修改的文件:"
for f in "${MODIFIED_FILES[@]}"; do
    echo "   ~ $f"
done
echo ""
echo "📋 后续步骤:"
echo "   1. 在 S${TYPE}_${NAME}System.cs 的 AddComponents() 中添加业务逻辑"
if [[ "$SYNC_CLIENT" == "true" ]]; then
    echo "   2. 在 C${TYPE}_${NAME}System.cs 的 AddComponents() 中添加客户端表现"
fi
echo "   3. 在 AbilityM_${NAME}.csv 中填入数据行"
echo "   4. 按需在 AbilityM_${NAME}.cs 中添加计算属性（D_ 前缀）"

# ============================================================
# 输出执行日志（供 AI Agent 查阅）
# ============================================================
LOG_DIR="${PROJECT_ROOT}/harness/temp"
mkdir -p "$LOG_DIR"
LOG_FILE="${LOG_DIR}/ability-gen-${NAME}-$(date +%Y%m%d_%H%M%S).log"

{
    echo "═══════════════════════════════════════════════════════"
    echo "  工具: ability-gen.sh"
    echo "  时间: $(date '+%Y-%m-%d %H:%M:%S')"
    echo "  参数: --name ${NAME} --type ${TYPE} --sync-client ${SYNC_CLIENT}"
    echo "═══════════════════════════════════════════════════════"
    echo ""
    echo "📁 新建文件 (${#CREATED_FILES[@]} 个):"
    for f in "${CREATED_FILES[@]}"; do
        echo "  [新建] $f"
    done
    echo ""
    echo "📝 修改文件 (${#MODIFIED_FILES[@]} 个):"
    for f in "${MODIFIED_FILES[@]}"; do
        echo "  [修改] $f"
    done
    echo ""
    echo "📋 后续步骤:"
    echo "  1. 在 S${TYPE}_${NAME}System.cs 的 AddComponents() 中添加业务逻辑"
    if [[ "$SYNC_CLIENT" == "true" ]]; then
        echo "  2. 在 C${TYPE}_${NAME}System.cs 的 AddComponents() 中添加客户端表现"
    fi
    echo "  3. 在 AbilityM_${NAME}.csv 中填入数据行"
    echo "  4. 按需在 AbilityM_${NAME}.cs 中添加计算属性（D_ 前缀）"
} > "$LOG_FILE"

echo ""
echo "📋 执行日志已保存: $LOG_FILE"
