#!/usr/bin/env bash
# =============================================================================
# scene-gen.sh — 完整场景创建流水线（自动化工具）
#
# 功能：一键创建新场景的完整注册链路
#   1. 在 Map.cs 注册地图 ID 常量 + Data 数组条目
#   2. 在 SceneData.cs 注册场景数据条目
#   3. 创建 SceneConfig.asset（最小可用模板）
#   4. 复制客户端场景文件（如指定 --copy-from）
#   5. 写入服务端转换配置（强制步骤，不可跳过）
#
# 工作流（两步式，AI 必须完整执行）：
#   Step A: 运行本脚本 → 完成所有注册和文件创建 + 输出服务端配置
#   Step B: AI 必须调用 MCP → execute_menu_item "Tools/功能/场景/AI场景转换"
#           Unity 执行：删除旧服务端场景(如有) → 打开场景 → 优化 → 另存为 Server 前缀 → 注册 BuildSettings
#   ❌ 跳过 Step B = 流水线不完整！
#
# 用法：
#   bash scene-gen.sh \
#     --name LevelTest_04 \
#     --display-name "新地图" \
#     --sign NewMap \
#     --project-root /path/to/unity/project
#
# 参数：
#   必须：
#     --name NAME           场景名（如 LevelTest_04），同时用于 SceneConfig、SceneData
#     --display-name TEXT   中文显示名（如 "新地图"），用于 Map.cs
#     --sign SIGN           Map Sign 标识符（如 "NewMap"），同时作为 Map.cs 的 Id_ 后缀
#     --project-root PATH   Unity 项目根目录
#
#   可选（Map.cs 相关）：
#     --map-id ID           Map ID（不指定则从 Map.cs 中自动递增 max+1）
#     --res-sign SIGN       Map ResSign（默认 = --sign）
#     --res-icon ICON       Map ResIcon（默认 = "MapNew"）
#     --mode-switch-res RES Map ModeSwitchRes（默认 = --sign）
#     --sort N              Map 排序值（默认 0）
#     --is-default          Map 是否默认地图（出现即为 true，默认 false）
#
#   可选（SceneConfig 相关）：
#     --mode MODE           SceneConfig Mode 整数（默认 5）
#     --weapon1 ID          武器1 ID（默认 14）
#     --weapon2 ID          武器2 ID（默认 43）
#     --super-weapon ID     超级武器 ID（默认 10）
#
#   可选（SceneData 相关）：
#     --stage-sign TEXT     SceneData StageSign（默认 = --name）
#     --element-config TEXT SceneData ElementConfig（默认 = --name）
#     --festival-asset      StageSign 使用 FestivalAssetData.GetMapAsset("...") 包装
#
#   可选（场景文件相关）：
#     --copy-from SOURCE    从指定场景复制 .unity 文件
#     --scene-dir DIR       场景目录（默认 Assets/Scenes/Runtime）
#
#   可选（跳过步骤）：
#     --skip-map            跳过 Map.cs 注册
#     --skip-scene-data     跳过 SceneData.cs 注册
#     --skip-config         跳过 SceneConfig.asset 创建
#     （注意：服务端场景生成为强制步骤，不可跳过）
#
# OUTPUT FILES (供 Phase 4 技术文档 S-05 引用):
#   CREATE: Assets/Bundle/Configs/Scene/{Name}.asset
#           — SceneConfig (YAML, 包含 Mode/武器/场景引用)
#   CREATE: Assets/Scenes/Runtime/{Name}.unity
#           — 客户端场景文件 (条件: --copy-from 指定时复制)
#   CREATE: Assets/Scripts/Data/SceneData_AutoGenerated.cs
#           — partial class (仅首次创建，后续追加)
#   CREATE: Temp/AIGC_SceneConvertConfig.txt
#           — 服务端转换配置 (供 Unity MCP Step B 读取)
#   MODIFY: Assets/Scripts/Template/data/Map.cs
#           — 插入 Id_{Sign} 常量 + Data 数组条目
#   MODIFY: Assets/Scripts/Data/SceneData_AutoGenerated.cs
#           — datas.Add() 注册场景数据
#   REQUIRE_MCP: execute_menu_item "Tools/功能/场景/AI场景转换"
#           — 产出 Assets/Scenes/Runtime/Server{Name}.unity (服务端场景)
# =============================================================================

set -euo pipefail

# ─── 默认值 ─────────────────────────────────────────────────
NAME=""
DISPLAY_NAME=""
SIGN=""
PROJECT_ROOT=""
MAP_ID=""
RES_SIGN=""
RES_ICON="MapNew"
MODE_SWITCH_RES=""
MODE=5
WEAPON1=14
WEAPON2=43
SUPER_WEAPON=10
SORT=0
IS_DEFAULT="false"
COPY_FROM=""
SCENE_DIR=""
STAGE_SIGN=""
ELEMENT_CONFIG=""
FESTIVAL_ASSET=false
SKIP_MAP=false
SKIP_SCENE_DATA=false
SKIP_CONFIG=false

# ─── 参数解析 ───────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --name)              NAME="$2";              shift 2 ;;
        --display-name)      DISPLAY_NAME="$2";      shift 2 ;;
        --sign)              SIGN="$2";              shift 2 ;;
        --project-root)      PROJECT_ROOT="$2";      shift 2 ;;
        --map-id)            MAP_ID="$2";            shift 2 ;;
        --res-sign)          RES_SIGN="$2";          shift 2 ;;
        --res-icon)          RES_ICON="$2";          shift 2 ;;
        --mode-switch-res)   MODE_SWITCH_RES="$2";   shift 2 ;;
        --mode)              MODE="$2";              shift 2 ;;
        --weapon1)           WEAPON1="$2";           shift 2 ;;
        --weapon2)           WEAPON2="$2";           shift 2 ;;
        --super-weapon)      SUPER_WEAPON="$2";      shift 2 ;;
        --sort)              SORT="$2";              shift 2 ;;
        --is-default)        IS_DEFAULT="true";      shift   ;;
        --copy-from)         COPY_FROM="$2";         shift 2 ;;
        --scene-dir)         SCENE_DIR="$2";         shift 2 ;;
        --stage-sign)        STAGE_SIGN="$2";        shift 2 ;;
        --element-config)    ELEMENT_CONFIG="$2";    shift 2 ;;
        --festival-asset)    FESTIVAL_ASSET=true;    shift   ;;
        --skip-map)          SKIP_MAP=true;          shift   ;;
        --skip-scene-data)   SKIP_SCENE_DATA=true;   shift   ;;
        --skip-config)       SKIP_CONFIG=true;       shift   ;;
        *)
            echo "❌ 未知参数: $1" >&2
            echo "用法: bash scene-gen.sh --name NAME --display-name TEXT --sign SIGN --project-root PATH [options]" >&2
            exit 1
            ;;
    esac
done

# ─── 必须参数验证 ───────────────────────────────────────────
if [[ -z "$NAME" ]]; then echo "❌ 缺少必要参数: --name" >&2; exit 1; fi
if [[ -z "$DISPLAY_NAME" ]]; then echo "❌ 缺少必要参数: --display-name" >&2; exit 1; fi
if [[ -z "$SIGN" ]]; then echo "❌ 缺少必要参数: --sign" >&2; exit 1; fi
if [[ -z "$PROJECT_ROOT" ]]; then echo "❌ 缺少必要参数: --project-root" >&2; exit 1; fi
if [[ ! -d "$PROJECT_ROOT" ]]; then echo "❌ 项目目录不存在: $PROJECT_ROOT" >&2; exit 1; fi

# ─── 路径配置（自动检测项目布局）────────────────────────────────
CODEGEN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$CODEGEN_DIR/path-config.sh"
[[ -z "$SCENE_DIR" ]] && SCENE_DIR="$SCENES_RUNTIME"

# ─── 可选参数默认值 ─────────────────────────────────────────
[[ -z "$RES_SIGN" ]] && RES_SIGN="$SIGN"
[[ -z "$MODE_SWITCH_RES" ]] && MODE_SWITCH_RES="$SIGN"
[[ -z "$STAGE_SIGN" ]] && STAGE_SIGN="$NAME"
[[ -z "$ELEMENT_CONFIG" ]] && ELEMENT_CONFIG="$NAME"

# ─── 文件路径 ───────────────────────────────────────────────
MAP_FILE="$PROJECT_ROOT/$SCRIPTS_BASE/Template/data/Map.cs"
SCENE_DATA_AUTO_FILE="$PROJECT_ROOT/$SCRIPTS_BASE/Data/SceneData_AutoGenerated.cs"
SCENE_CONFIG_DIR="$PROJECT_ROOT/$BUNDLE_CONFIGS/Scene"
SCENE_CONFIG_FILE="$SCENE_CONFIG_DIR/${NAME}.asset"
SCENE_FULL_DIR="$PROJECT_ROOT/$SCENE_DIR"

# 验证关键文件
if [[ "$SKIP_MAP" == false && ! -f "$MAP_FILE" ]]; then
    echo "❌ Map.cs 不存在: $MAP_FILE" >&2; exit 1
fi
# SceneData_AutoGenerated.cs 不存在时会自动创建，无需预检

echo "═══════════════════════════════════════════════════════"
echo "  场景创建流水线启动"
echo "  场景名: $NAME"
echo "  显示名: $DISPLAY_NAME"
echo "  Sign:   $SIGN"
echo "═══════════════════════════════════════════════════════"
echo ""

# ═══════════════════════════════════════════════════════════
# Step 1: Map.cs 注册（ID 常量 + Data 数组条目）
# ═══════════════════════════════════════════════════════════
if [[ "$SKIP_MAP" == false ]]; then
    echo "── Step 1: 注册 Map.cs ──────────────────────────"

    # 幂等检查
    if grep -q "Id_${SIGN}" "$MAP_FILE"; then
        echo "⚠️  Map.cs 中已存在 Id_${SIGN}，跳过注册"
        # 从已有条目读取 MAP_ID（供后续 SceneData 引用）
        MAP_ID=$(grep "Id_${SIGN}" "$MAP_FILE" | grep -oE '= [0-9]+' | head -1 | grep -oE '[0-9]+')
    else
        # ── 自动分配 Map ID ──
        if [[ -z "$MAP_ID" ]]; then
            MAP_ID=$(grep -oE 'public const int Id_\w+\s*=\s*[0-9]+' "$MAP_FILE" \
                | grep -oE '[0-9]+$' | sort -n | tail -1)
            MAP_ID=$((MAP_ID + 1))
            echo "  自动分配 Map ID: $MAP_ID"
        fi

        # ── 插入 ID 常量（2个TAB缩进，紧跟在最后一个 Id_ 常量之后）──
        LAST_ID_LINE=$(grep -n 'public const int Id_' "$MAP_FILE" | tail -1 | cut -d: -f1)
        if [[ -z "$LAST_ID_LINE" ]]; then
            echo "❌ Map.cs 中未找到 Id_ 常量声明" >&2; exit 1
        fi

        awk -v insert_after="$LAST_ID_LINE" -v sign="$SIGN" -v map_id="$MAP_ID" '
        {
            print
            if (NR == insert_after) {
                printf "\t\tpublic const int Id_%s = %s;\n", sign, map_id
            }
        }
        ' "$MAP_FILE" > "${MAP_FILE}.tmp" && mv "${MAP_FILE}.tmp" "$MAP_FILE"
        echo "  ✅ 已添加 ID 常量: Id_${SIGN} = ${MAP_ID}"

        # ── 插入 Data 数组条目（5个TAB + ", new Map(...)"）──
        # 格式: new Map( id, "中文名", "Sign", "ResSign", "ResIcon", isDefault, sort, "ModeSwitchRes" )
        DATA_CLOSE_LINE=$(awk '/Data = new Map\[\]/{found=1} found && /};/{print NR; exit}' "$MAP_FILE")
        if [[ -z "$DATA_CLOSE_LINE" ]]; then
            echo "❌ Map.cs 中未找到 Data 数组闭合 };" >&2; exit 1
        fi

        # 写入新条目到临时文件（避免 awk -v 引号转义问题）
        MAP_ENTRY_TMP=$(mktemp)
        printf '\t\t\t\t\t, new Map( %s, "%s", "%s", "%s", "%s", %s, %s, "%s" )\n' \
            "$MAP_ID" "$DISPLAY_NAME" "$SIGN" "$RES_SIGN" "$RES_ICON" "$IS_DEFAULT" "$SORT" "$MODE_SWITCH_RES" \
            > "$MAP_ENTRY_TMP"

        awk -v insert_before="$DATA_CLOSE_LINE" -v entry_file="$MAP_ENTRY_TMP" '
        {
            if (NR == insert_before) {
                while ((getline line < entry_file) > 0) print line
                close(entry_file)
            }
            print
        }
        ' "$MAP_FILE" > "${MAP_FILE}.tmp" && mv "${MAP_FILE}.tmp" "$MAP_FILE"
        rm -f "$MAP_ENTRY_TMP"
        echo "  ✅ 已添加 Data 数组条目: new Map( ${MAP_ID}, \"${DISPLAY_NAME}\", ... )"
    fi
    echo ""
fi

# ═══════════════════════════════════════════════════════════
# Step 2: SceneData_AutoGenerated.cs 注册
# ═══════════════════════════════════════════════════════════
if [[ "$SKIP_SCENE_DATA" == false ]]; then
    echo "── Step 2: 注册 SceneData_AutoGenerated.cs ──────"

    # 如果文件不存在，创建初始模板
    if [[ ! -f "$SCENE_DATA_AUTO_FILE" ]]; then
        cat > "$SCENE_DATA_AUTO_FILE" << 'AUTOGEN_TEMPLATE'
// ─────────────────────────────────────────────────────
// 本文件由 scene-gen.sh 自动生成，请勿手动修改。
// 手写场景数据请编辑 SceneData.cs
// ─────────────────────────────────────────────────────
using Sofunny.BiuBiuBiu2.Template;

namespace Sofunny.BiuBiuBiu2.Data {
    public partial class SceneData {
        static SceneData() {
            // [GENERATED_SCENE_DATA] — 以下由 scene-gen.sh 自动生成，请勿手动修改
            // [END_GENERATED_SCENE_DATA]
        }
    }
}
AUTOGEN_TEMPLATE
        echo "  ✅ 已创建 SceneData_AutoGenerated.cs 模板"
    fi

    # 幂等检查
    if grep -q "MapSet.Id_${SIGN}" "$SCENE_DATA_AUTO_FILE"; then
        echo "⚠️  SceneData_AutoGenerated.cs 中已存在 MapSet.Id_${SIGN}，跳过"
    else
        # 构建 StageSign 值
        if [[ "$FESTIVAL_ASSET" == true ]]; then
            STAGE_SIGN_VALUE="FestivalAssetData.GetMapAsset(\"${STAGE_SIGN}\")"
        else
            STAGE_SIGN_VALUE="\"${STAGE_SIGN}\""
        fi

        # 构建新注册行
        NEW_REGISTRATION="            datas.Add(new Data { ID = MapSet.Id_${SIGN}, StageSign = ${STAGE_SIGN_VALUE}, ElementConfig = \"${ELEMENT_CONFIG}\" });"

        # 在 [END_GENERATED_SCENE_DATA] 标记前插入新行
        MARKER_LINE=$(grep -n '\[END_GENERATED_SCENE_DATA\]' "$SCENE_DATA_AUTO_FILE" | head -1 | cut -d: -f1)
        if [[ -z "$MARKER_LINE" ]]; then
            echo "❌ SceneData_AutoGenerated.cs 中未找到 [END_GENERATED_SCENE_DATA] 标记" >&2; exit 1
        fi

        # 写入注册行到临时文件
        REG_TMP=$(mktemp)
        echo "$NEW_REGISTRATION" > "$REG_TMP"

        awk -v insert_before="$MARKER_LINE" -v entry_file="$REG_TMP" '
        {
            if (NR == insert_before) {
                while ((getline line < entry_file) > 0) print line
                close(entry_file)
            }
            print
        }
        ' "$SCENE_DATA_AUTO_FILE" > "${SCENE_DATA_AUTO_FILE}.tmp" && mv "${SCENE_DATA_AUTO_FILE}.tmp" "$SCENE_DATA_AUTO_FILE"
        rm -f "$REG_TMP"
        echo "  ✅ 已注册: datas.Add(new Data { ID = MapSet.Id_${SIGN}, ... })"
    fi
    echo ""
fi

# ═══════════════════════════════════════════════════════════
# Step 3: 创建 SceneConfig.asset（最小可用模板）
# ═══════════════════════════════════════════════════════════
if [[ "$SKIP_CONFIG" == false ]]; then
    echo "── Step 3: 创建 SceneConfig.asset ────────────────"

    mkdir -p "$SCENE_CONFIG_DIR"

    if [[ -f "$SCENE_CONFIG_FILE" ]]; then
        echo "⚠️  SceneConfig.asset 已存在: ${SCENE_CONFIG_FILE##*/}，跳过"
    else
        # SceneConfig.cs 的 m_Script GUID: 279347f6c779d9042af5ef9df1fb27cc
        cat > "$SCENE_CONFIG_FILE" << YAML_EOF
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!114 &11400000
MonoBehaviour:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_GameObject: {fileID: 0}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 11500000, guid: 279347f6c779d9042af5ef9df1fb27cc, type: 3}
  m_Name: ${NAME}
  m_EditorClassIdentifier: 
  TargetScenePath: ${SCENE_DIR}/${NAME}.unity
  Mode: ${MODE}
  Weapon1Id: ${WEAPON1}
  Weapon2Id: ${WEAPON2}
  SuperWeaponId: ${SUPER_WEAPON}
  PlayerSpawnPoints: []
  AISpawnPoints: []
  ElementSpawnPoints: []
  RoomAreas: []
  DummySpawnPoints: []
  MonsterWaveSpawners: []
  ScenePoints: []
YAML_EOF
        echo "  ✅ 已创建 SceneConfig.asset: $BUNDLE_CONFIGS/Scene/${NAME}.asset"
        echo "  ⚠️  注意: PlayerSpawnPoints 等详细数据需后续在 Unity 中填入"
    fi
    echo ""
fi

# ═══════════════════════════════════════════════════════════
# Step 4: 复制客户端场景（如指定 --copy-from）
# ═══════════════════════════════════════════════════════════
if [[ -n "$COPY_FROM" ]]; then
    echo "── Step 4: 复制客户端场景 ───────────────────────"

    # --copy-from 支持: 完整相对路径(Assets/...) 或 简单场景名
    if [[ "$COPY_FROM" == Assets/* ]]; then
        # 完整相对路径：去掉末尾 .unity（如有），再统一加上
        SRC_SCENE="$PROJECT_ROOT/${COPY_FROM%.unity}.unity"
    else
        SRC_SCENE="$SCENE_FULL_DIR/${COPY_FROM%.unity}.unity"
    fi
    TARGET_SCENE="$SCENE_FULL_DIR/${NAME}.unity"

    if [[ ! -f "$SRC_SCENE" ]]; then
        echo "❌ 源场景文件不存在: $SRC_SCENE" >&2
        exit 1
    fi
    if [[ -f "$TARGET_SCENE" ]]; then
        echo "⚠️  目标场景已存在，将覆盖: ${NAME}.unity"
    fi

    mkdir -p "$SCENE_FULL_DIR"
    cp "$SRC_SCENE" "$TARGET_SCENE"
    # 不复制 .meta 文件 —— Unity 会自动生成新的 GUID
    echo "  ✅ 场景复制完成: ${COPY_FROM%.unity} → ${NAME}.unity"
    echo ""
fi

# ═══════════════════════════════════════════════════════════
# Step 5: 服务端场景转换配置（强制步骤，不可跳过）
# ═══════════════════════════════════════════════════════════
echo "── Step 5: 服务端场景转换配置（强制）────────────────"

CONFIG_FILE="$PROJECT_ROOT/Temp/AIGC_SceneConvertConfig.txt"
mkdir -p "$(dirname "$CONFIG_FILE")"
echo "$NAME" > "$CONFIG_FILE"
echo "  ✅ 配置文件写入: Temp/AIGC_SceneConvertConfig.txt"
echo ""
echo "  ⚠️  强制下一步: AI Agent 必须调用 Unity MCP 执行场景优化"
echo "     → execute_menu_item \"Tools/功能/场景/AI场景转换\""
echo "     Unity 将自动: 打开场景 → 删除旧服务端场景(如有) → 优化 → 另存为 Server${NAME} → 注册 EditorBuildSettings"
echo "     ❌ 不执行此步骤 = 流水线不完整！"

# ═══════════════════════════════════════════════════════════
# 完成汇总
# ═══════════════════════════════════════════════════════════
echo ""
echo "═══════════════════════════════════════════════════════"
echo "  场景创建流水线完成（bash 部分）"
echo ""
echo "  已完成:"
[[ "$SKIP_MAP" == false ]]        && echo "    ✅ Map.cs:       Id_${SIGN} = ${MAP_ID:-auto}"
[[ "$SKIP_SCENE_DATA" == false ]] && echo "    ✅ SceneData_AutoGenerated.cs: MapSet.Id_${SIGN}"
[[ "$SKIP_CONFIG" == false ]]     && echo "    ✅ SceneConfig:  $BUNDLE_CONFIGS/Scene/${NAME}.asset"
[[ -n "$COPY_FROM" ]]            && echo "    ✅ 场景文件:    ${SCENE_DIR}/${NAME}.unity"
echo "    ⏳ 服务端场景:  待 MCP 执行 (Server${NAME})"
echo ""
echo "  ⚠️ 必须执行的后续操作:"
echo "    1. 【强制】调用 MCP: execute_menu_item \"Tools/功能/场景/AI场景转换\""
echo "    2. Unity Refresh 以加载新资产"
echo "    3. 在 Unity Scene 编辑器中配置 PlayerSpawnPoints 等数据"
echo "═══════════════════════════════════════════════════════"

# ═══════════════════════════════════════════════════════════
# 输出执行日志（供 AI Agent 查阅）
# ═══════════════════════════════════════════════════════════
LOG_DIR="${PROJECT_ROOT}/harness/temp"
mkdir -p "$LOG_DIR"
LOG_FILE="${LOG_DIR}/scene-gen-${NAME}-$(date +%Y%m%d_%H%M%S).log"

CREATED_FILES=()
MODIFIED_FILES=()
[[ "$SKIP_MAP" == false ]]        && MODIFIED_FILES+=("$MAP_FILE")
[[ "$SKIP_SCENE_DATA" == false ]] && { [[ -f "$SCENE_DATA_AUTO_FILE" ]] && MODIFIED_FILES+=("$SCENE_DATA_AUTO_FILE") || CREATED_FILES+=("$SCENE_DATA_AUTO_FILE"); }
[[ "$SKIP_CONFIG" == false ]]     && CREATED_FILES+=("${SCENE_CONFIG_DIR}/${NAME}.asset")
[[ -n "$COPY_FROM" ]]            && CREATED_FILES+=("${SCENE_FULL_DIR}/${NAME}.unity")
CREATED_FILES+=("${PROJECT_ROOT}/Temp/AIGC_SceneConvertConfig.txt")

{
    echo "═══════════════════════════════════════════════════════"
    echo "  工具: scene-gen.sh"
    echo "  时间: $(date '+%Y-%m-%d %H:%M:%S')"
    echo "  参数: --name ${NAME} --display-name ${DISPLAY_NAME} --sign ${SIGN}"
    if [[ -n "$COPY_FROM" ]]; then echo "         --copy-from ${COPY_FROM}"; fi
    echo "═══════════════════════════════════════════════════════"
    echo ""
    echo "📁 新建文件 (${#CREATED_FILES[@]} 个):"
    for f in "${CREATED_FILES[@]}"; do
        echo "  [新建] $f"
    done
    echo ""
    echo "📝 修改文件 (${#MODIFIED_FILES[@]} 个):"
    for f in "${MODIFIED_FILES[@]}"; do
        echo "  [修改] $f"
    done
    echo ""
    echo "⏳ 待生成（MCP 执行后）:"
    echo "  [待生成] ${SCENE_FULL_DIR}/Server${NAME}.unity"
    echo ""
    echo "📋 后续步骤（强制）:"
    echo "  1. 【强制】调用 MCP: execute_menu_item \"Tools/功能/场景/AI场景转换\""
    echo "  2. Unity Refresh 以加载新资产"
    echo "  3. 在 Unity Scene 编辑器中配置 PlayerSpawnPoints 等数据"
} > "$LOG_FILE"

echo ""
echo "📋 执行日志已保存: $LOG_FILE"
