from __future__ import annotations

import sys
from pathlib import Path


ANCHOR_DIR_NAME = ".tharness"
MANIFEST_NAME = "project.yaml"
AGENTS_NAME = "AGENTS.md"
AGENTS_BLOCK_START = "<!-- THARNESS_BINDING_START -->"
AGENTS_BLOCK_END = "<!-- THARNESS_BINDING_END -->"


def resolve_existing_dir(path_value: str) -> Path:
    path = Path(path_value).expanduser()
    if not path.exists():
        raise FileNotFoundError(f"目标目录不存在: {path}")
    if not path.is_dir():
        raise ValueError(f"目标路径不是目录: {path}")
    return path.resolve()


def anchor_dir(project_root: Path) -> Path:
    return project_root / ANCHOR_DIR_NAME


def manifest_path(project_root: Path) -> Path:
    return anchor_dir(project_root) / MANIFEST_NAME


def relative_to_project(project_root: Path, path: Path) -> str:
    try:
        return path.relative_to(project_root).as_posix()
    except ValueError:
        return str(path)


def ps_single_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def write_generated_file(path: Path, content: str, force: bool) -> bool:
    if path.exists():
        existing = path.read_text(encoding="utf-8-sig")
        if existing == content:
            return False
        if not force:
            raise FileExistsError(f"文件已存在且内容不同，请使用 --force 覆盖: {path}")

    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def agents_bridge_content(tharness_root: Path) -> str:
    return "\n".join(
        [
            AGENTS_BLOCK_START,
            "# THarness 绑定入口",
            "",
            "本项目已绑定到 THarness 主工程。AI 在本项目启动后，必须先读取并遵守以下入口：",
            "",
            f"1. `{tharness_root / 'AGENTS.md'}`",
            f"2. `{tharness_root / 'AIGC' / 'INDEX.md'}`",
            "",
            "启动边界：",
            "",
            "- 通用框架、角色、规则、wiki、capabilities 和工具改动写回 THarness 主工程。",
            "- 项目事实、项目代码、项目资源和项目专属决策只写入当前目标项目。",
            "- 如果当前 AI 环境无法读取 THarness 主工程路径，应先向用户请求把 THarness 主工程加入可读工作区或提供入口内容。",
            "",
            AGENTS_BLOCK_END,
            "",
        ]
    )


def merge_agents_content(existing: str, block: str) -> str:
    start = existing.find(AGENTS_BLOCK_START)
    end = existing.find(AGENTS_BLOCK_END)
    if start >= 0 and end >= start:
        end += len(AGENTS_BLOCK_END)
        merged = existing[:start].rstrip() + "\n\n" + block.rstrip() + "\n" + existing[end:].lstrip()
        return merged.rstrip() + "\n"

    if not existing.strip():
        return block

    return existing.rstrip() + "\n\n" + block


def write_agents_bridge(project_root: Path, tharness_root: Path) -> bool:
    path = project_root / AGENTS_NAME
    existing = path.read_text(encoding="utf-8-sig") if path.exists() else ""
    content = merge_agents_content(existing, agents_bridge_content(tharness_root))
    if existing == content:
        return False
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def manifest_content(tharness_root: Path, project_root: Path) -> str:
    return "\n".join(
        [
            "# Generated by THarness. This file points this project to the main framework.",
            f"tharness_root: {tharness_root}",
            f"project_root: {project_root}",
            "framework_entry: AIGC/INDEX.md",
            "role_entry: AIGC/roles/INDEX.md",
            "wiki_entry: AIGC/wiki/INDEX.md",
            "write_policy: framework_changes_go_to_tharness_root_project_facts_stay_in_project",
            "",
        ]
    )


def powershell_launcher_content(tharness_root: Path) -> str:
    tool = tharness_root / "tools" / "tharness.py"
    return "\n".join(
        [
            '$ErrorActionPreference = "Stop"',
            "$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path",
            "$ProjectRoot = Split-Path -Parent $ScriptDir",
            f"$TharnessTool = {ps_single_quote(str(tool))}",
            "$Python = (Get-Command python -ErrorAction SilentlyContinue).Source",
            f"if (-not $Python) {{ $Python = {ps_single_quote(sys.executable)} }}",
            "& $Python $TharnessTool project start --root $ProjectRoot",
            "",
        ]
    )


def cmd_launcher_content(tharness_root: Path) -> str:
    tool = tharness_root / "tools" / "tharness.py"
    return "\n".join(
        [
            "@echo off",
            'set "PROJECT_ROOT=%~dp0.."',
            "where python >nul 2>nul",
            "if %ERRORLEVEL%==0 (",
            f'  python "{tool}" project start --root "%PROJECT_ROOT%"',
            ") else (",
            f'  "{sys.executable}" "{tool}" project start --root "%PROJECT_ROOT%"',
            ")",
            "exit /b %ERRORLEVEL%",
            "",
        ]
    )


def readme_content(tharness_root: Path) -> str:
    return "\n".join(
        [
            "# THarness Project Anchor",
            "",
            "This directory is a lightweight launcher for the shared THarness framework.",
            "It does not copy `AIGC/`; it only points this project to the main framework root.",
            "",
            "## Start",
            "",
            "```powershell",
            ".\\.tharness\\start.ps1",
            "```",
            "",
            "## Main Framework",
            "",
            f"`{tharness_root}`",
            "",
            "Framework, role, wiki, capability, and tool improvements should be made in the main framework root.",
            "Project facts and project-specific code should stay in the current project.",
            "",
        ]
    )


def run_project_init(tharness_root: Path, root_value: str, force: bool) -> int:
    project_root = resolve_existing_dir(root_value)
    target_anchor = anchor_dir(project_root)
    target_anchor.mkdir(exist_ok=True)

    files = {
        target_anchor / MANIFEST_NAME: manifest_content(tharness_root, project_root),
        target_anchor / "start.ps1": powershell_launcher_content(tharness_root),
        target_anchor / "start.cmd": cmd_launcher_content(tharness_root),
        target_anchor / "README.md": readme_content(tharness_root),
    }

    changed = []
    unchanged = []
    for path, content in files.items():
        if write_generated_file(path, content, force):
            changed.append(path)
        else:
            unchanged.append(path)

    agents_path = project_root / AGENTS_NAME
    if write_agents_bridge(project_root, tharness_root):
        changed.append(agents_path)
    else:
        unchanged.append(agents_path)

    print("project-init: PASS")
    print(f"INFO  project_root: {project_root}")
    print(f"INFO  tharness_root: {tharness_root}")
    for path in changed:
        print(f"INFO  written: {relative_to_project(project_root, path)}")
    for path in unchanged:
        print(f"INFO  unchanged: {relative_to_project(project_root, path)}")
    print("INFO  start: .tharness\\start.ps1")
    print("INFO  ai-entry: AGENTS.md")
    return 0


def startup_packet(tharness_root: Path, project_root: Path, manifest_exists: bool) -> list[str]:
    manifest_state = "found" if manifest_exists else "not found; using transient startup"
    return [
        "project-start: PASS",
        f"INFO  project_root: {project_root}",
        f"INFO  tharness_root: {tharness_root}",
        f"INFO  manifest: {manifest_state}",
        "read-order:",
        f"  - {tharness_root / 'AIGC' / 'INDEX.md'}",
        f"  - {tharness_root / 'AIGC' / 'roles' / 'INDEX.md'}",
        f"  - {tharness_root / 'AIGC' / 'roles' / 'common' / 'RULE.md'}",
        f"  - {tharness_root / 'AIGC' / 'roles' / 'role-manager' / 'RULE.md'}",
        "write-policy:",
        "  - 通用框架、角色、规则、wiki、capabilities 和工具改动写入 tharness_root。",
        "  - 项目事实、项目代码、项目资源和项目专属决策只写入 project_root。",
        "  - 候选通用改动先按 THarness 写入位置路由判断，再同步回主工程。",
        "ai-startup:",
        "  - 目标项目根目录 AGENTS.md 是 AI 自动启动桥接入口。",
        f"  - 启动后先读取 {tharness_root / 'AGENTS.md'} 和 {tharness_root / 'AIGC' / 'INDEX.md'}。",
        "handoff:",
        "  - 将上面的 project_root 作为目标项目上下文。",
        "  - 将上面的 tharness_root 作为唯一 THarness 主工程。",
    ]


def run_project_start(tharness_root: Path, root_value: str) -> int:
    project_root = resolve_existing_dir(root_value)
    has_manifest = manifest_path(project_root).exists()
    for line in startup_packet(tharness_root, project_root, has_manifest):
        print(line)
    return 0


def run_project_command(tharness_root: Path, project_command: str | None, root_value: str, force: bool) -> int:
    command = project_command or "start"
    try:
        if command == "init":
            return run_project_init(tharness_root, root_value, force)
        if command == "start":
            return run_project_start(tharness_root, root_value)

        print("错误: 未知 project 命令。可用命令: init, start", file=sys.stderr)
        return 2
    except (FileExistsError, FileNotFoundError, ValueError) as exc:
        print(f"错误: {exc}", file=sys.stderr)
        return 2
